import {initializeModeration,restriction,assertCanWrite,submitReport,listReports,setRestriction,clearRestriction,resolveReport,publicationConsentVersion} from './moderation.mjs';
import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {serve,database,json,body,text,email,fail} from './common.mjs';
import {initializeAdmin,recordEvent,adminOverview} from './admin-store.mjs';
const db=database('auth');db.exec('CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,password TEXT,salt TEXT,profile TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user TEXT,expires INTEGER);');initializeAdmin(db);initializeModeration(db);
const hash=t=>createHash('sha256').update(t).digest('hex');
function user(id){const row=db.prepare('SELECT id,email,profile FROM users WHERE id=?').get(id);if(!row)fail('Sesión no válida',401);return {...row,profile:JSON.parse(row.profile),restriction:restriction(db,id)};}
function session(token){const row=db.prepare('SELECT user FROM sessions WHERE token=? AND expires>?').get(hash(token||''),Date.now());if(!row)fail('Inicia sesión',401);return user(row.user);}
const attempts=new Map();function limit(key,max=20){const now=Date.now();if(attempts.size>5000)for(const [k,v] of attempts)if(v.until<now)attempts.delete(k);let r=attempts.get(key);if(!r||r.until<now)r={n:0,until:now+600000};r.n++;attempts.set(key,r);if(r.n>max)fail('Demasiados intentos. Espera diez minutos.',429);}
function publicJunior(row){const p=JSON.parse(row.profile);return {id:row.id,name:p.name,headline:p.headline||'',description:p.description||'',studies:p.studies||'',vocationalTraining:p.vocationalTraining||'',languages:p.languages||'',skills:p.skills||'',internships:p.internships||'',contribution:p.contribution||'',location:p.location||'',availability:p.availability||'',portfolio:p.portfolio||''};}
export const server=serve('auth',async(req,res,url)=>{
 if(url.pathname==='/health'&&req.method==='GET'){db.prepare('SELECT 1').get();json(res,{ready:true});return;}
 if(req.method==='POST'&&['/register','/login'].includes(url.pathname)){const b=await body(req),mail=email(b.email);limit('ip:'+(req.headers['x-client-ip']||'local'),50);limit('account:'+mail,20);if(typeof b.password!=='string'||b.password.length<10||b.password.length>200)fail('La contraseña debe tener entre 10 y 200 caracteres');let row=db.prepare('SELECT * FROM users WHERE email=?').get(mail);
 if(url.pathname==='/register'){if(row)fail('Ya existe una cuenta con este correo',409);if(b.accountType!==undefined&&!['junior','company'].includes(b.accountType))fail('Selecciona Junior o Empresa');const id=randomUUID(),salt=randomBytes(16).toString('hex');db.prepare('INSERT INTO users(id,email,password,salt,profile,created_at) VALUES(?,?,?,?,?,?)').run(id,mail,scryptSync(b.password,salt,64).toString('hex'),salt,JSON.stringify({name:text(b.name,100)||'Mi perfil',accountType:b.accountType||null,skills:'',publicProfile:false,alerts:true}),new Date().toISOString());row=db.prepare('SELECT * FROM users WHERE id=?').get(id);recordEvent(db,id,'register');}
 else{const expected=row?Buffer.from(row.password,'hex'):Buffer.alloc(64),actual=scryptSync(b.password,row?.salt||'dummy',64);if(!row||!timingSafeEqual(expected,actual))fail('Correo o contraseña incorrectos',401);}
 db.prepare('UPDATE users SET last_login=? WHERE id=?').run(new Date().toISOString(),row.id);recordEvent(db,row.id,'login');const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),row.id,Date.now()+7*86400000);json(res,{token,user:user(row.id)});return;}
 if(url.pathname==='/moderation/check'&&req.method==='GET'){const id=req.headers['x-user'];if(!id||!db.prepare('SELECT id FROM users WHERE id=?').get(id))fail('Usuario no encontrado',404);json(res,restriction(db,id));return;}
 const u=session(req.headers['x-session']);

 if(url.pathname==='/reports'&&req.method==='POST'){json(res,submitReport(db,u.id,await body(req)),201);return;}
 if(url.pathname==='/admin/reports'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,listReports(db,url.searchParams));return;}
 if(url.pathname==='/admin/audit'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,{items:db.prepare("SELECT a.*,json_extract(t.profile,'$.name') AS targetName,json_extract(u.profile,'$.name') AS actorName FROM moderation_actions a LEFT JOIN users t ON t.id=a.target_user LEFT JOIN users u ON u.id=a.actor ORDER BY a.created_at DESC LIMIT 100").all().map(r=>({...r,details:JSON.parse(r.details)}))});return;}
 const ban=url.pathname.match(/^\/admin\/users\/([^/]+)\/restriction$/);if(ban){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);if(req.method==='POST'){json(res,setRestriction(db,u.id,ban[1],await body(req)));return;}if(req.method==='DELETE'){json(res,clearRestriction(db,u.id,ban[1],await body(req)));return;}}
 const report=url.pathname.match(/^\/admin\/reports\/([^/]+)$/);if(report&&req.method==='PATCH'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,resolveReport(db,u.id,report[1],await body(req)));return;}
 if(url.pathname==='/activity'&&req.method==='POST'){const b=await body(req);if(!['reaction_updated','comment_created','comment_deleted','post_reposted','offer_created','offer_updated','offer_deleted','contribution_created','contribution_updated','contribution_deleted'].includes(b.type))fail('Evento no válido');recordEvent(db,u.id,b.type,{title:text(b.title),offerId:text(b.id)});json(res,{ok:true});return;}
 if(url.pathname==='/hiring/profile'&&req.method==='GET'){if(u.profile.accountType!=='junior')fail('Perfil de candidato no disponible',403);assertCanWrite(db,u.id);json(res,publicJunior({id:u.id,profile:JSON.stringify(u.profile)}));return;}
 if(url.pathname==='/me'&&req.method==='GET'){json(res,u);return;}
 if(url.pathname==='/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(hash(req.headers['x-session']));recordEvent(db,u.id,'logout');json(res,{ok:true});return;}
 if(url.pathname==='/workspace'&&req.method==='POST'){if(u.profile.role!=='admin')fail('Solo administradores pueden alternar espacios',403);const b=await body(req);if(!['junior','company'].includes(b.accountType))fail('Selecciona Junior o Empresa');const groups={junior:['headline','description','studies','vocationalTraining','languages','skills','internships','contribution','location','availability','portfolio','publicProfile'],company:['companyName','description','business','location','website','contactEmail']};const previous=u.profile.accountType;if(!u.profile.workspaceProfiles)u.profile.workspaceProfiles={};if(groups[previous])u.profile.workspaceProfiles[previous]=Object.fromEntries(groups[previous].filter(k=>u.profile[k]!==undefined).map(k=>[k,u.profile[k]]));for(const k of new Set([...groups.junior,...groups.company]))delete u.profile[k];Object.assign(u.profile,u.profile.workspaceProfiles[b.accountType]||{});u.profile.accountType=b.accountType;db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);recordEvent(db,u.id,'workspace_changed',{status:b.accountType});json(res,user(u.id));return;}
 if(url.pathname==='/type'&&req.method==='POST'){const b=await body(req);if(!['junior','company'].includes(b.accountType))fail('Selecciona Junior o Empresa');if(u.profile.accountType&&u.profile.accountType!==b.accountType)fail('El tipo de cuenta ya está seleccionado',409);u.profile.accountType=b.accountType;db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);json(res,u);return;}
 if(url.pathname==='/profile'&&req.method==='PATCH'){const b=await body(req);if(!u.profile.accountType)fail('Selecciona un tipo de cuenta',428);if(u.restriction.active&&!(u.profile.accountType==='junior'&&b.publicProfile===false&&Object.keys(b).length===1))assertCanWrite(db,u.id);if(u.profile.accountType==='junior'&&b.publicProfile===true&&u.profile.publicProfile!==true){if(b.acceptedPublication!==true||b.publicationConsentVersion!==publicationConsentVersion)fail('Confirma que quieres compartir los campos de tu perfil',400);}const fields=u.profile.accountType==='junior'?['name','headline','description','studies','vocationalTraining','languages','skills','internships','contribution','location','availability','portfolio']:['name','companyName','description','business','location','website','contactEmail'];for(const field of fields)if(b[field]!==undefined)u.profile[field]=text(b[field],['description','contribution','studies','vocationalTraining','internships'].includes(field)?5000:1000);if(!u.profile.name)fail('Indica tu nombre');for(const field of ['portfolio','website'])if(b[field]){try{if(!['https:','http:'].includes(new URL(b[field]).protocol))fail('Enlace no válido');}catch{fail('Enlace no válido');}}if(b.contactEmail)u.profile.contactEmail=email(b.contactEmail);if(u.profile.accountType==='junior'&&b.publicProfile===true&&u.profile.publicProfile!==true){db.prepare('INSERT INTO profile_consents VALUES(?,?,?,?)').run(randomUUID(),u.id,publicationConsentVersion,new Date().toISOString());}if(u.profile.accountType==='junior'&&typeof b.publicProfile==='boolean')u.profile.publicProfile=b.publicProfile;db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);recordEvent(db,u.id,'profile_updated');json(res,u);return;}
 if(url.pathname==='/juniors'&&req.method==='GET'){const q=text(url.searchParams.get('q'),100).toLowerCase();const all=db.prepare('SELECT id,profile FROM users').all().filter(row=>{const p=JSON.parse(row.profile);return p.accountType==='junior'&&p.publicProfile===true;}).map(publicJunior).filter(p=>!q||[p.name,p.headline,p.skills,p.studies,p.vocationalTraining,p.location].join(' ').toLowerCase().includes(q));const page=Math.max(1,Math.min(1000,Number.parseInt(url.searchParams.get('page'))||1));json(res,{items:all.slice((page-1)*20,page*20),total:all.length,page,pageSize:20});return;}
 if(url.pathname.startsWith('/juniors/')&&req.method==='GET'){const row=db.prepare('SELECT id,profile FROM users WHERE id=?').get(url.pathname.split('/')[2]);if(!row)fail('Perfil no encontrado',404);const p=JSON.parse(row.profile);if(p.accountType!=='junior'||p.publicProfile!==true)fail('Perfil no publicado',404);json(res,publicJunior(row));return;}
 if(url.pathname==='/admin/overview'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);const result=adminOverview(db,url.searchParams);result.users=result.users.map(person=>({...person,restriction:restriction(db,person.id)}));json(res,result);return;}
 fail('Ruta no encontrada',404);
});
