import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {createRemoteJWKSet,jwtVerify} from 'jose';
import {serve,database,json,body,text,email,fail} from './common.mjs';
const db=database('auth');db.exec('CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,password TEXT,salt TEXT,profile TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS oauth(state TEXT PRIMARY KEY,user TEXT,nonce TEXT,expires INTEGER);');
import {initializeAdmin,recordEvent,adminOverview,eventLabels} from './admin-store.mjs';
initializeAdmin(db);
const hash=t=>createHash('sha256').update(t).digest('hex');
function user(id){const u=db.prepare('SELECT id,email,profile FROM users WHERE id=?').get(id);if(!u)fail('Sesión no válida',401);return {...u,profile:JSON.parse(u.profile)};}
function session(token){const s=db.prepare('SELECT user FROM sessions WHERE token=? AND expires>?').get(hash(token||''),Date.now());if(!s)fail('Inicia sesión',401);return user(s.user);}
const attempts=new Map();function limit(key){const now=Date.now(),v=attempts.get(key)||{n:0,until:now+600000};if(v.until<now){v.n=0;v.until=now+600000;}v.n++;attempts.set(key,v);if(v.n>20)fail('Demasiados intentos. Espera diez minutos.',429);}
export const server=serve('auth',async(req,res,url)=>{
 if(req.method==='POST'&&['/register','/login'].includes(url.pathname)){const b=await body(req),mail=email(b.email);limit((req.headers['x-client-ip']||'local')+mail);if(typeof b.password!=='string'||b.password.length<10||b.password.length>200)fail('La contraseña debe tener entre 10 y 200 caracteres');let u=db.prepare('SELECT * FROM users WHERE email=?').get(mail);if(url.pathname==='/register'){if(u)fail('Ya existe una cuenta con este correo',409);const salt=randomBytes(16).toString('hex'),id=randomUUID();db.prepare('INSERT INTO users(id,email,password,salt,profile) VALUES(?,?,?,?,?)').run(id,mail,scryptSync(b.password,salt,64).toString('hex'),salt,JSON.stringify({name:text(b.name)||'Mi perfil',skills:'',premium:'unknown',linkedin:false,alerts:true}));u=db.prepare('SELECT * FROM users WHERE id=?').get(id);}else{const expected=u?Buffer.from(u.password,'hex'):Buffer.alloc(64);const actual=scryptSync(b.password,u?.salt||'dummy',64);if(!u||!timingSafeEqual(expected,actual))fail('Correo o contraseña incorrectos',401);}const now=new Date().toISOString();if(url.pathname==='/register'){db.prepare('UPDATE users SET created_at=? WHERE id=?').run(now,u.id);recordEvent(db,u.id,'register');}db.prepare('UPDATE users SET last_login=? WHERE id=?').run(now,u.id);recordEvent(db,u.id,'login');const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),u.id,Date.now()+7*86400000);json(res,{token,user:user(u.id)});return;}
 if(url.pathname==='/linkedin/callback'){const state=url.searchParams.get('state'),o=db.prepare('SELECT * FROM oauth WHERE state=? AND expires>?').get(state||'',Date.now());if(!o)fail('Conexión expirada. Inténtalo de nuevo');db.prepare('DELETE FROM oauth WHERE state=?').run(state);if(url.searchParams.get('error'))fail('Se canceló la conexión con LinkedIn');const r=await fetch('https://www.linkedin.com/oauth/v2/accessToken',{method:'POST',body:new URLSearchParams({grant_type:'authorization_code',code:url.searchParams.get('code')||'',redirect_uri:process.env.LINKEDIN_REDIRECT_URI,client_id:process.env.LINKEDIN_CLIENT_ID,client_secret:process.env.LINKEDIN_CLIENT_SECRET}),signal:AbortSignal.timeout(10000)});const tokens=await r.json();if(!r.ok||!tokens.id_token)fail('LinkedIn no autorizó la conexión');const {payload}=await jwtVerify(tokens.id_token,createRemoteJWKSet(new URL('https://www.linkedin.com/oauth/openid/jwks')),{issuer:'https://www.linkedin.com/oauth',audience:process.env.LINKEDIN_CLIENT_ID});if(payload.nonce!==o.nonce)fail('Validación de LinkedIn incorrecta');const u=user(o.user);u.profile.linkedin=true;u.profile.linkedinName=text(payload.name);u.profile.linkedinConnectedAt=new Date().toISOString();db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);recordEvent(db,u.id,'linkedin_connected');json(res,{connected:true});return;}
 const u=session(req.headers['x-session']);
 if(url.pathname==='/events'&&req.method==='POST'){const b=await body(req);if(!eventLabels[b.type])fail('Evento no válido');recordEvent(db,u.id,b.type,b.details);json(res,{ok:true});return;}
 if(url.pathname==='/admin/overview'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,adminOverview(db,url.searchParams));return;}
 if(url.pathname==='/me'&&req.method==='GET'){json(res,u);return;}
 if(url.pathname==='/admin/status'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,{users:db.prepare('SELECT COUNT(*) AS count FROM users').get().count,activeSessions:db.prepare('SELECT COUNT(*) AS count FROM sessions WHERE expires>?').get(Date.now()).count,role:'admin'});return;}
 if(url.pathname==='/logout'){recordEvent(db,u.id,'logout');db.prepare('DELETE FROM sessions WHERE token=?').run(hash(req.headers['x-session']));json(res,{ok:true});return;}
 if(url.pathname==='/profile'&&req.method==='PATCH'){const b=await body(req);u.profile={...u.profile,name:text(b.name)||u.profile.name,skills:text(b.skills,3000),premium:['yes','no','unknown'].includes(b.premium)?b.premium:'unknown',alerts:b.alerts!==false};db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);recordEvent(db,u.id,'profile_updated');json(res,u);return;}
 if(url.pathname==='/linkedin/start'){if(!process.env.LINKEDIN_CLIENT_ID||!process.env.LINKEDIN_CLIENT_SECRET)fail('Configura las credenciales de LinkedIn en el servidor para conectar tu cuenta',503);const state=randomBytes(32).toString('hex'),nonce=randomBytes(32).toString('hex');db.prepare('INSERT INTO oauth VALUES(?,?,?,?)').run(state,u.id,nonce,Date.now()+600000);json(res,{url:'https://www.linkedin.com/oauth/v2/authorization?'+new URLSearchParams({response_type:'code',client_id:process.env.LINKEDIN_CLIENT_ID,redirect_uri:process.env.LINKEDIN_REDIRECT_URI,scope:'openid profile email',state,nonce})});return;}
 fail('Ruta no encontrada',404);
});
