import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {serve,database,json,body,text,email,fail} from './common.mjs';
import {initializeAdmin,recordEvent,adminOverview} from './admin-store.mjs';
const db=database('auth');db.exec('CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,password TEXT,salt TEXT,profile TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user TEXT,expires INTEGER);');initializeAdmin(db);
const hash=t=>createHash('sha256').update(t).digest('hex');
function user(id){const row=db.prepare('SELECT id,email,profile FROM users WHERE id=?').get(id);if(!row)fail('Sesión no válida',401);return {...row,profile:JSON.parse(row.profile)};}
function session(token){const row=db.prepare('SELECT user FROM sessions WHERE token=? AND expires>?').get(hash(token||''),Date.now());if(!row)fail('Inicia sesión',401);return user(row.user);}
const attempts=new Map();function limit(key){const now=Date.now();let r=attempts.get(key);if(!r||r.until<now)r={n:0,until:now+600000};r.n++;attempts.set(key,r);if(r.n>20)fail('Demasiados intentos. Espera diez minutos.',429);}
function publicJunior(row){const p=JSON.parse(row.profile);return {id:row.id,name:p.name,headline:p.headline||'',description:p.description||'',studies:p.studies||'',vocationalTraining:p.vocationalTraining||'',languages:p.languages||'',skills:p.skills||'',internships:p.internships||'',contribution:p.contribution||'',location:p.location||'',availability:p.availability||'',portfolio:p.portfolio||''};}
export const server=serve('auth',async(req,res,url)=>{
 if(req.method==='POST'&&['/register','/login'].includes(url.pathname)){const b=await body(req),mail=email(b.email);limit((req.headers['x-client-ip']||'local')+mail);if(typeof b.password!=='string'||b.password.length<10||b.password.length>200)fail('La contraseña debe tener entre 10 y 200 caracteres');let row=db.prepare('SELECT * FROM users WHERE email=?').get(mail);
 if(url.pathname==='/register'){if(row)fail('Ya existe una cuenta con este correo',409);if(b.accountType!==undefined&&!['junior','company'].includes(b.accountType))fail('Selecciona Junior o Empresa');const id=randomUUID(),salt=randomBytes(16).toString('hex');db.prepare('INSERT INTO users(id,email,password,salt,profile,created_at) VALUES(?,?,?,?,?,?)').run(id,mail,scryptSync(b.password,salt,64).toString('hex'),salt,JSON.stringify({name:text(b.name,100)||'Mi perfil',accountType:b.accountType||null,skills:'',publicProfile:false,alerts:true}),new Date().toISOString());row=db.prepare('SELECT * FROM users WHERE id=?').get(id);recordEvent(db,id,'register');}
 else{const expected=row?Buffer.from(row.password,'hex'):Buffer.alloc(64),actual=scryptSync(b.password,row?.salt||'dummy',64);if(!row||!timingSafeEqual(expected,actual))fail('Correo o contraseña incorrectos',401);}
 db.prepare('UPDATE users SET last_login=? WHERE id=?').run(new Date().toISOString(),row.id);recordEvent(db,row.id,'login');const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),row.id,Date.now()+7*86400000);json(res,{token,user:user(row.id)});return;}
 const u=session(req.headers['x-session']);
 if(url.pathname==='/activity'&&req.method==='POST'){const b=await body(req);if(!['offer_created','offer_updated','offer_deleted','contribution_created','contribution_updated','contribution_deleted'].includes(b.type))fail('Evento no válido');recordEvent(db,u.id,b.type,{title:text(b.title),offerId:text(b.id)});json(res,{ok:true});return;}
 if(url.pathname==='/me'&&req.method==='GET'){json(res,u);return;}
 if(url.pathname==='/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(hash(req.headers['x-session']));recordEvent(db,u.id,'logout');json(res,{ok:true});return;}
 if(url.pathname==='/type'&&req.method==='POST'){const b=await body(req);if(!['junior','company'].includes(b.accountType))fail('Selecciona Junior o Empresa');if(u.profile.accountType&&u.profile.accountType!==b.accountType)fail('El tipo de cuenta ya está seleccionado',409);u.profile.accountType=b.accountType;db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);json(res,u);return;}
 if(url.pathname==='/profile'&&req.method==='PATCH'){const b=await body(req);if(!u.profile.accountType)fail('Selecciona un tipo de cuenta',428);const fields=u.profile.accountType==='junior'?['name','headline','description','studies','vocationalTraining','languages','skills','internships','contribution','location','availability','portfolio']:['name','companyName','description','business','location','website','contactEmail'];for(const field of fields)if(b[field]!==undefined)u.profile[field]=text(b[field],['description','contribution','studies','vocationalTraining','internships'].includes(field)?5000:1000);if(!u.profile.name)fail('Indica tu nombre');for(const field of ['portfolio','website'])if(b[field]){try{if(!['https:','http:'].includes(new URL(b[field]).protocol))fail('Enlace no válido');}catch{fail('Enlace no válido');}}if(b.contactEmail)u.profile.contactEmail=email(b.contactEmail);if(u.profile.accountType==='junior'&&typeof b.publicProfile==='boolean')u.profile.publicProfile=b.publicProfile;db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(u.profile),u.id);recordEvent(db,u.id,'profile_updated');json(res,u);return;}
 if(url.pathname==='/juniors'&&req.method==='GET'){const q=text(url.searchParams.get('q'),100).toLowerCase();const all=db.prepare('SELECT id,profile FROM users').all().filter(row=>{const p=JSON.parse(row.profile);return p.accountType==='junior'&&p.publicProfile===true;}).map(publicJunior).filter(p=>!q||[p.name,p.headline,p.skills,p.studies,p.vocationalTraining,p.location].join(' ').toLowerCase().includes(q));const page=Math.max(1,Math.min(1000,Number.parseInt(url.searchParams.get('page'))||1));json(res,{items:all.slice((page-1)*20,page*20),total:all.length,page,pageSize:20});return;}
 if(url.pathname.startsWith('/juniors/')&&req.method==='GET'){const row=db.prepare('SELECT id,profile FROM users WHERE id=?').get(url.pathname.split('/')[2]);if(!row)fail('Perfil no encontrado',404);const p=JSON.parse(row.profile);if(p.accountType!=='junior'||p.publicProfile!==true)fail('Perfil no publicado',404);json(res,publicJunior(row));return;}
 if(url.pathname==='/admin/overview'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,adminOverview(db,url.searchParams));return;}
 fail('Ruta no encontrada',404);
});
