import {initializeHiring,createHiring} from './hiring.mjs';
import {randomUUID} from 'node:crypto';
import {serve,database,json,body,text,fail,call} from './common.mjs';
const db=database('community');
db.exec(`CREATE TABLE IF NOT EXISTS offers(id TEXT PRIMARY KEY,owner TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS posts(id TEXT PRIMARY KEY,owner TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS offers_owner ON offers(owner); CREATE INDEX IF NOT EXISTS posts_owner ON posts(owner);
CREATE TABLE IF NOT EXISTS reactions(post TEXT REFERENCES posts(id) ON DELETE CASCADE,user TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(post,user));
CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,post TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,user TEXT NOT NULL,author TEXT NOT NULL,content TEXT NOT NULL,images TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS comments_post ON comments(post,created_at);`);
initializeHiring(db);const hiring=createHiring(db);
const unpack=row=>({...JSON.parse(row.data),id:row.id,ownerId:row.owner,createdAt:row.created_at,updatedAt:row.updated_at});
function image(value){if(!value)return '';if(typeof value!=='string'||value.length>700000)fail('Imagen demasiado grande: máximo 500 KB');const match=value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+=*)$/);if(!match)fail('Usa una imagen PNG, JPEG o WebP');const bytes=Buffer.from(match[2],'base64');if(bytes.length>500000)fail('Imagen demasiado grande: máximo 500 KB');const valid=match[1]==='png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):match[1]==='jpeg'?bytes[0]===255&&bytes[1]===216:bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)fail('Imagen no válida');return value;}
function images(value){if(value===undefined)return [];if(!Array.isArray(value)||value.length>4)fail('Máximo cuatro imágenes por publicación o comentario');return value.map(image).filter(Boolean);}
function offer(input,author){if(input.yearsExperience!==undefined||input.experienceYears!==undefined)fail('Las ofertas junior no admiten requisitos de años de experiencia');const data={title:text(input.title,150),description:text(input.description,15000),salary:text(input.salary,300),location:text(input.location,300),modality:['remote','hybrid','onsite','unspecified'].includes(input.modality)?input.modality:'unspecified',languages:text(input.languages,2000),degrees:text(input.degrees,3000),vocationalTraining:text(input.vocationalTraining,3000),internships:text(input.internships,3000),skills:text(input.skills,2000),status:['published','draft','closed'].includes(input.status)?input.status:'draft',image:image(input.image),companyName:author};if(!data.title||!data.description)fail('Indica título y descripción');return data;}
function post(input,author){const data={title:text(input.title,150),content:text(input.content,20000),tags:text(input.tags,1000),kind:['project','research','contribution'].includes(input.kind)?input.kind:'contribution',status:input.status==='published'?'published':'draft',authorName:author,images:images(input.images)};if(!data.title||!data.content)fail('Indica título y contenido');return data;}
function getPost(id){const row=db.prepare('SELECT * FROM posts WHERE id=?').get(id);if(!row)fail('Publicación no encontrada',404);return unpack(row);}
function visible(p,user){if(p.status!=='published'&&p.ownerId!==user)fail('Publicación no encontrada',404);}
function publicPost(id){const p=getPost(id);if(p.status!=='published')fail('Solo puedes interactuar con publicaciones publicadas',404);return p;}
function enrich(p,user){let original;if(p.originalId){const row=db.prepare('SELECT * FROM posts WHERE id=?').get(p.originalId);original=row?unpack(row):null;const available=original?.status==='published';p={...p,title:available?original.title:'Publicación original no disponible',content:'',tags:'',images:[],original:available?{id:original.id,ownerId:original.ownerId,authorName:original.authorName,title:original.title,content:original.content,kind:original.kind,tags:original.tags,images:original.images||[]}:null,originalUnavailable:!available};}const counts=db.prepare('SELECT value,COUNT(*) AS n FROM reactions WHERE post=? GROUP BY value').all(p.id);return {...p,images:p.images||[],likes:counts.find(r=>r.value==='like')?.n||0,dislikes:counts.find(r=>r.value==='dislike')?.n||0,myReaction:db.prepare('SELECT value FROM reactions WHERE post=? AND user=?').get(p.id,user)?.value||null,commentCount:db.prepare('SELECT COUNT(*) AS n FROM comments WHERE post=?').get(p.id).n,repostCount:db.prepare("SELECT COUNT(*) AS n FROM posts WHERE json_extract(data,'$.originalId')=? AND json_extract(data,'$.status')='published'").get(p.id).n};}
async function canWrite(user){const r=await call('auth','/moderation/check',{headers:{'x-user':user}});if(r.active)fail('No puedes publicar contenido: '+r.reason+(r.until?' · Hasta '+r.until:' · Bloqueo permanente'),403);}
export const server=serve('community',async(req,res,url)=>{
 if(url.pathname==='/health'&&req.method==='GET'){db.prepare('SELECT 1').get();json(res,{ready:true});return;}
 const user=req.headers['x-user'],type=req.headers['x-account-type'];if(!user||!['junior','company'].includes(type))fail('No autorizado',403);const author=decodeURIComponent(req.headers['x-author-name']||'Miembro');
 if(await hiring(req,res,url,{user,type,author}))return;
 const parts=url.pathname.split('/').filter(Boolean),table=parts[0];if(!['offers','posts'].includes(table))fail('Ruta no encontrada',404);
 if(table==='posts'&&parts.length>=3){const p=getPost(parts[1]);visible(p,user);const action=parts[2];if(req.method!=='GET')await canWrite(user);
  if(action==='reaction'&&parts.length===3&&req.method==='PUT'){publicPost(p.id);const b=await body(req);if(!['like','dislike',null].includes(b.value))fail('Selecciona Me gusta, No me gusta o quitar reacción');if(b.value===null)db.prepare('DELETE FROM reactions WHERE post=? AND user=?').run(p.id,user);else db.prepare('INSERT INTO reactions VALUES(?,?,?) ON CONFLICT(post,user) DO UPDATE SET value=excluded.value').run(p.id,user,b.value);json(res,enrich(p,user));return;}
  if(action==='comments'&&parts.length===3&&req.method==='GET'){const page=Math.max(1,Number.parseInt(url.searchParams.get('page'))||1);const total=db.prepare('SELECT COUNT(*) AS n FROM comments WHERE post=?').get(p.id).n;const items=db.prepare('SELECT * FROM comments WHERE post=? ORDER BY created_at,id LIMIT 20 OFFSET ?').all(p.id,(page-1)*20).map(r=>({id:r.id,postId:r.post,ownerId:r.user,authorName:r.author,content:r.content,images:JSON.parse(r.images),createdAt:r.created_at}));json(res,{items,total,page,pageSize:20});return;}
  if(action==='comments'&&parts.length===3&&req.method==='POST'){publicPost(p.id);const b=await body(req,3000000),content=text(b.content,4000),photos=images(b.images);if(!content&&!photos.length)fail('Escribe un comentario o añade una imagen');const n=db.prepare('SELECT COUNT(*) AS n FROM comments WHERE user=? AND created_at>?').get(user,new Date(Date.now()-86400000).toISOString()).n;if(n>=100)fail('Máximo cien comentarios por día',429);const id=randomUUID(),now=new Date().toISOString();db.prepare('INSERT INTO comments VALUES(?,?,?,?,?,?,?)').run(id,p.id,user,author,content,JSON.stringify(photos),now);json(res,{id,postId:p.id,ownerId:user,authorName:author,content,images:photos,createdAt:now},201);return;}
  if(action==='comments'&&parts.length===4&&req.method==='GET'){const r=db.prepare('SELECT * FROM comments WHERE id=? AND post=?').get(parts[3],p.id);if(!r)fail('Comentario no encontrado',404);json(res,{id:r.id,ownerId:r.user,content:r.content,authorName:r.author});return;}
  if(action==='comments'&&parts.length===4&&req.method==='DELETE'){const row=db.prepare('SELECT user FROM comments WHERE id=? AND post=?').get(parts[3],p.id);if(!row)fail('Comentario no encontrado',404);if(row.user!==user)fail('Solo puedes eliminar tus comentarios',403);db.prepare('DELETE FROM comments WHERE id=?').run(parts[3]);json(res,{ok:true});return;}
  if(action==='repost'&&parts.length===3&&req.method==='POST'){publicPost(p.id);const original=p.originalId?publicPost(p.originalId):p;if(original.ownerId===user)fail('Esta publicación ya es tuya');const existing=db.prepare("SELECT * FROM posts WHERE owner=? AND json_extract(data,'$.originalId')=?").get(user,original.id);if(existing){json(res,enrich(unpack(existing),user));return;}if(db.prepare('SELECT COUNT(*) AS n FROM posts WHERE owner=?').get(user).n>=200)fail('Límite de 200 publicaciones por cuenta',429);const id=randomUUID(),now=new Date().toISOString(),data={title:original.title,content:'',tags:'',kind:'repost',status:'published',authorName:author,originalId:original.id,originalAuthorName:original.authorName,originalAuthorId:original.ownerId,images:[]};db.prepare('INSERT INTO posts VALUES(?,?,?,?,?)').run(id,user,JSON.stringify(data),now,now);json(res,enrich({...data,id,ownerId:user,createdAt:now,updatedAt:now},user),201);return;}
  fail('Ruta no encontrada',404);
 }
 if(parts.length>2)fail('Ruta no encontrada',404);
 if(req.method==='GET'&&!parts[1]){const mine=url.searchParams.get('mine')==='true',q=text(url.searchParams.get('q'),100).toLowerCase(),page=Math.max(1,Math.min(1000,Number.parseInt(url.searchParams.get('page'))||1));const rows=mine?db.prepare('SELECT * FROM '+table+' WHERE owner=? ORDER BY created_at DESC,id').all(user):db.prepare('SELECT * FROM '+table+' ORDER BY created_at DESC,id').all();const data=rows.map(unpack).filter(item=>mine||item.status==='published').map(p=>table==='posts'?enrich(p,user):({...p,discarded:!!db.prepare('SELECT 1 FROM offer_decisions WHERE offer_id=? AND user_id=?').get(p.id,user)})).filter(p=>table!=='offers'||mine||(url.searchParams.get('discarded')==='true'?p.discarded:!p.discarded)).filter(item=>!q||[item.title,item.description,item.content,item.original?.content,item.companyName,item.tags,item.skills].join(' ').toLowerCase().includes(q));json(res,{items:data.slice((page-1)*20,page*20),total:data.length,page,pageSize:20});return;}
 let existing;if(parts[1]){const row=db.prepare('SELECT * FROM '+table+' WHERE id=?').get(parts[1]);if(!row)fail('No encontrado',404);existing=unpack(row);}
 if(req.method==='GET'&&existing){visible(existing,user);json(res,table==='posts'?enrich(existing,user):{...existing,discarded:!!db.prepare('SELECT 1 FROM offer_decisions WHERE offer_id=? AND user_id=?').get(existing.id,user)});return;}
 if(!['POST','PATCH','DELETE'].includes(req.method))fail('Método no permitido',405);await canWrite(user);
 if(existing&&existing.ownerId!==user)fail('No puedes modificar contenido de otra cuenta',403);
 if(type!==(table==='offers'?'company':'junior')&&!(table==='posts'&&existing?.originalId&&req.method==='DELETE'))fail(table==='offers'?'Solo las empresas pueden publicar ofertas':'Solo los juniors pueden publicar aportaciones',403);
 if(req.method==='DELETE'&&existing){db.prepare('DELETE FROM '+table+' WHERE id=? AND owner=?').run(existing.id,user);json(res,{ok:true});return;}
 if(existing?.originalId)fail('Una republicación mantiene el original. Puedes eliminarla y volver a compartirla.');
 if(req.method==='POST'&&parts[1]||req.method==='PATCH'&&!existing)fail('Ruta no válida',404);
 const input=await body(req,3000000),merged={...existing,...input};if(input.originalId!==undefined)fail('Usa el botón Republicar para conservar la atribución');const data=table==='offers'?offer(merged,author):post(merged,author),now=new Date().toISOString();
 if(existing){db.prepare('UPDATE '+table+' SET data=?,updated_at=? WHERE id=? AND owner=?').run(JSON.stringify(data),now,existing.id,user);json(res,table==='posts'?enrich({...data,id:existing.id,ownerId:user,createdAt:existing.createdAt,updatedAt:now},user):{...data,id:existing.id,ownerId:user,createdAt:existing.createdAt,updatedAt:now});return;}
 if(db.prepare('SELECT COUNT(*) AS n FROM '+table+' WHERE owner=?').get(user).n>=200)fail('Límite de 200 entradas por cuenta',429);const id=randomUUID();db.prepare('INSERT INTO '+table+' VALUES(?,?,?,?,?)').run(id,user,JSON.stringify(data),now,now);const result={...data,id,ownerId:user,createdAt:now,updatedAt:now};json(res,table==='posts'?enrich(result,user):result,201);
});
