import {randomUUID} from 'node:crypto';
import {serve,database,json,body,text,fail} from './common.mjs';
const db=database('community');
db.exec('CREATE TABLE IF NOT EXISTS offers(id TEXT PRIMARY KEY,owner TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS posts(id TEXT PRIMARY KEY,owner TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS offers_owner ON offers(owner); CREATE INDEX IF NOT EXISTS posts_owner ON posts(owner);');
const unpack=row=>({...JSON.parse(row.data),id:row.id,ownerId:row.owner,createdAt:row.created_at,updatedAt:row.updated_at});
function image(value){if(!value)return '';if(typeof value!=='string'||value.length>700000)fail('Imagen demasiado grande: máximo 500 KB');const match=value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+=*)$/);if(!match)fail('Usa una imagen PNG, JPEG o WebP');const bytes=Buffer.from(match[2],'base64');if(bytes.length>500000)fail('Imagen demasiado grande: máximo 500 KB');const valid=match[1]==='png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):match[1]==='jpeg'?bytes[0]===255&&bytes[1]===216:bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)fail('Imagen no válida');return value;}
function offer(input,author){if(input.yearsExperience!==undefined||input.experienceYears!==undefined)fail('Las ofertas junior no admiten requisitos de años de experiencia');const data={title:text(input.title,150),description:text(input.description,15000),salary:text(input.salary,300),location:text(input.location,300),modality:['remote','hybrid','onsite','unspecified'].includes(input.modality)?input.modality:'unspecified',languages:text(input.languages,2000),degrees:text(input.degrees,3000),vocationalTraining:text(input.vocationalTraining,3000),internships:text(input.internships,3000),skills:text(input.skills,2000),status:['published','draft','closed'].includes(input.status)?input.status:'draft',image:image(input.image),companyName:author};if(!data.title||!data.description)fail('Indica título y descripción');return data;}
function post(input,author){const data={title:text(input.title,150),content:text(input.content,20000),tags:text(input.tags,1000),kind:['project','research','contribution'].includes(input.kind)?input.kind:'contribution',status:input.status==='published'?'published':'draft',authorName:author};if(!data.title||!data.content)fail('Indica título y contenido');return data;}
export const server=serve('community',async(req,res,url)=>{
 const user=req.headers['x-user'],type=req.headers['x-account-type'];if(!user||!['junior','company'].includes(type))fail('No autorizado',403);
 const parts=url.pathname.split('/').filter(Boolean),table=parts[0];if(!['offers','posts'].includes(table)||parts.length>2)fail('Ruta no encontrada',404);const author=decodeURIComponent(req.headers['x-author-name']||'Miembro');
 if(req.method==='GET'&&!parts[1]){const mine=url.searchParams.get('mine')==='true',q=text(url.searchParams.get('q'),100).toLowerCase(),page=Math.max(1,Math.min(1000,Number.parseInt(url.searchParams.get('page'))||1));const rows=mine?db.prepare('SELECT * FROM '+table+' WHERE owner=? ORDER BY created_at DESC,id').all(user):db.prepare('SELECT * FROM '+table+' ORDER BY created_at DESC,id').all();const data=rows.map(unpack).filter(item=>(mine||item.status==='published')&&(!q||[item.title,item.description,item.content,item.companyName,item.tags,item.skills].join(' ').toLowerCase().includes(q)));json(res,{items:data.slice((page-1)*20,page*20),total:data.length,page,pageSize:20});return;}
 let existing;if(parts[1]){const row=db.prepare('SELECT * FROM '+table+' WHERE id=?').get(parts[1]);if(!row)fail('No encontrado',404);existing=unpack(row);}
 if(req.method==='GET'&&existing){if(existing.status!=='published'&&existing.ownerId!==user)fail('No encontrado',404);json(res,existing);return;}
 if(!['POST','PATCH','DELETE'].includes(req.method))fail('Método no permitido',405);if(type!==(table==='offers'?'company':'junior'))fail(table==='offers'?'Solo las empresas pueden publicar ofertas':'Solo los juniors pueden publicar aportaciones',403);
 if(existing&&existing.ownerId!==user)fail('No puedes modificar contenido de otra cuenta',403);
 if(req.method==='DELETE'&&existing){db.prepare('DELETE FROM '+table+' WHERE id=? AND owner=?').run(existing.id,user);json(res,{ok:true});return;}
 if(req.method==='POST'&&parts[1]||req.method==='PATCH'&&!existing)fail('Ruta no válida',404);
 const input=await body(req,800000),merged={...existing,...input};const data=table==='offers'?offer(merged,author):post(merged,author),now=new Date().toISOString();
 if(existing){db.prepare('UPDATE '+table+' SET data=?,updated_at=? WHERE id=? AND owner=?').run(JSON.stringify(data),now,existing.id,user);json(res,{...data,id:existing.id,ownerId:user,createdAt:existing.createdAt,updatedAt:now});return;}
 if(db.prepare('SELECT COUNT(*) AS n FROM '+table+' WHERE owner=?').get(user).n>=200)fail('Límite de 200 entradas por cuenta',429);const id=randomUUID();db.prepare('INSERT INTO '+table+' VALUES(?,?,?,?,?)').run(id,user,JSON.stringify(data),now,now);json(res,{...data,id,ownerId:user,createdAt:now,updatedAt:now},201);
});
