export function plainText(input=''){
 const entities={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};
 let s=String(input);for(let i=0;i<2;i++)s=s.replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(all,e)=>{if(e[0]!=='#')return entities[e.toLowerCase()]||all;const n=e[1].toLowerCase()==='x'?parseInt(e.slice(2),16):parseInt(e.slice(1),10);return n>=0&&n<=0x10ffff?String.fromCodePoint(n):'';});
 return s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<\/(p|div|li|h[1-6])>|<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/[\t ]+/g,' ').replace(/\n\s*\n/g,'\n\n').trim().slice(0,30000);
}
const dictionary=['React','TypeScript','JavaScript','Python','Java','SQL','Node.js','AWS','Azure','Docker','Kubernetes','Git','REST','HTML','CSS','Figma','Excel','Power BI','Salesforce','Linux','Go','C++','Angular','Vue','PostgreSQL','MongoDB'];
export function extractRequirements(description){const s=plainText(description);const skills=dictionary.filter(skill=>new RegExp('(^|[^a-z0-9])'+skill.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'([^a-z0-9]|$)','i').test(s));const education=s.split(/\n|(?<=[.!?])\s+/).filter(line=>/bachelor|master.?s|degree|licenciatura|titulaci[oó]n|grado universitario|formaci[oó]n profesional|doctorado|ph\.?d/i.test(line)).slice(0,4).map(x=>x.slice(0,500));return {skills:skills.join(', '),education:education.length?education.join('\n'):'No se ha identificado una titulación en el texto disponible.',educationDetected:education.length>0};}
export function safeUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function normalizeGreenhouse(job,source){const description=plainText(job.content||'');return{id:`greenhouse:${source.slug}:${job.id}`,externalId:String(job.id),provider:'greenhouse',source:'Greenhouse',sourceBoard:source.slug,title:plainText(job.title),company:source.company,location:job.location?.name||'No indicada',description:description||'Consulta la descripción en la oferta original.',url:safeUrl(job.absolute_url),publishedAt:job.updated_at||null,observedAt:new Date().toISOString(),salary:null,descriptionComplete:true,workplace:/remote|remoto/i.test(job.location?.name||'')?'Remoto':'No especificado',...extractRequirements(description)};}
export function normalizeLever(job,source){const description=plainText([job.descriptionPlain||job.description,...(job.lists||[]).map(l=>l.text+'\n'+l.content),job.additionalPlain||job.additional].filter(Boolean).join('\n'));const range=job.salaryRange;return{id:`lever:${source.slug}:${job.id}`,externalId:String(job.id),provider:'lever',source:'Lever',sourceBoard:source.slug,title:plainText(job.text),company:source.company,location:job.categories?.location||'No indicada',description:description||'Consulta la descripción en la oferta original.',url:safeUrl(job.hostedUrl),publishedAt:job.createdAt?new Date(job.createdAt).toISOString():null,observedAt:new Date().toISOString(),salary:range?{min:range.min,max:range.max,currency:range.currency,interval:range.interval||'No indicado',predicted:false}:null,descriptionComplete:true,workplace:job.workplaceType||'No especificado',...extractRequirements(description)};}
export function normalizeAdzuna(job,country){const description=plainText(job.description);return{id:`adzuna:${country}:${job.id}`,externalId:String(job.id),provider:'adzuna',source:'Adzuna',sourceBoard:country,title:plainText(job.title),company:job.company?.display_name||'No indicada',location:job.location?.display_name||'No indicada',description:description||'Consulta la descripción en la oferta original.',url:safeUrl(job.redirect_url),publishedAt:job.created||null,observedAt:new Date().toISOString(),salary:job.salary_min||job.salary_max?{min:job.salary_min,max:job.salary_max,currency:country==='gb'?'GBP':country==='us'?'USD':'EUR',interval:'año',predicted:Number(job.salary_is_predicted)===1}:null,descriptionComplete:false,workplace:'No especificado',...extractRequirements(description)};}
export function filterOffers(jobs,{q='',location='',company='',salaryOnly=false}){const terms=q.toLowerCase().split(/\s+/).filter(Boolean);return jobs.filter(j=>terms.every(t=>(j.title+' '+j.description).toLowerCase().includes(t))&&(!location||j.location.toLowerCase().includes(location.toLowerCase()))&&(!company||j.company===company)&&(!salaryOnly||j.salary&&!j.salary.predicted));}
