import {randomUUID} from 'node:crypto';
import {serve,database,json,body,text,fail} from './common.mjs';
import {normalizeGreenhouse,normalizeLever,normalizeAdzuna,filterOffers} from './discovery-model.mjs';
import {marketSummary} from './market-model.mjs';
import {companyInfo} from './company-data.mjs';
const db=database('discovery');db.exec('CREATE TABLE IF NOT EXISTS sources(id TEXT PRIMARY KEY,provider TEXT,slug TEXT,company TEXT, UNIQUE(provider,slug));');
if(!db.prepare('SELECT id FROM sources LIMIT 1').get())for(const [slug,company] of [['stripe','Stripe'],['datadog','Datadog'],['canonical','Canonical']])db.prepare('INSERT INTO sources VALUES(?,?,?,?)').run(randomUUID(),'greenhouse',slug,company);
const cache=new Map(),catalog=new Map();
const sources=()=>db.prepare('SELECT * FROM sources ORDER BY company').all();
async function remote(url){const response=await fetch(url,{headers:{Accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(12000)});if(!response.ok)fail('La fuente devolvió un error ('+response.status+')',502);const content=await response.text();if(content.length>10000000)fail('Respuesta de la fuente demasiado grande',502);return JSON.parse(content);}
async function board(source){const hit=cache.get(source.id);if(hit&&Date.now()-hit.time<300000)return hit;
 const url=source.provider==='greenhouse'?`https://boards-api.greenhouse.io/v1/boards/${encodeURIComponent(source.slug)}/jobs?content=true`:`https://api.lever.co/v0/postings/${encodeURIComponent(source.slug)}?mode=json`;
 const data=await remote(url);const raw=source.provider==='greenhouse'?data.jobs:data;if(!Array.isArray(raw))fail('La fuente no devolvió ofertas válidas',502);
 const jobs=raw.slice(0,2000).map(j=>source.provider==='greenhouse'?normalizeGreenhouse(j,source):normalizeLever(j,source));for(const j of jobs)catalog.set(j.id,j);const result={jobs,time:Date.now(),source:source.company};cache.set(source.id,result);return result;
}
export const server=serve('discovery',async(req,res,url)=>{
 if(url.pathname==='/market'){const list=sources();const outcomes=await Promise.allSettled(list.map(board));let jobs=[],reports=[];outcomes.forEach((r,i)=>{if(r.status==='fulfilled'){jobs.push(...r.value.jobs);reports.push({company:list[i].company,status:'ok',count:r.value.jobs.length});}else reports.push({company:list[i].company,status:'error',count:0});});json(res,marketSummary(jobs,reports));return;}
 if(url.pathname==='/company'&&req.method==='GET'){json(res,companyInfo(text(url.searchParams.get('name'),100)));return;}
 if(url.pathname==='/sources'&&req.method==='GET'){json(res,{boards:sources(),adzuna:!!(process.env.ADZUNA_APP_ID&&process.env.ADZUNA_APP_KEY),cacheMinutes:5});return;}
 if(url.pathname==='/sources'&&req.method==='POST'){const b=await body(req);if(!['greenhouse','lever'].includes(b.provider))fail('Proveedor no válido');if(!/^[a-zA-Z0-9_-]{1,80}$/.test(b.slug||''))fail('Identificador del portal no válido');const company=text(b.company,100);if(!company)fail('Indica la empresa');if(sources().length>=15)fail('Límite de 15 portales');const source={id:randomUUID(),provider:b.provider,slug:b.slug,company};await board(source);try{db.prepare('INSERT INTO sources VALUES(?,?,?,?)').run(source.id,source.provider,source.slug,company);}catch{fail('Ese portal ya está conectado',409);}json(res,source,201);return;}
 if(url.pathname.startsWith('/sources/')&&req.method==='DELETE'){const id=url.pathname.split('/')[2];const result=db.prepare('DELETE FROM sources WHERE id=?').run(id);if(!result.changes)fail('Fuente no encontrada',404);cache.delete(id);catalog.clear();json(res,{ok:true});return;}
 if(url.pathname==='/search'){
  const provider=url.searchParams.get('provider')||'boards';const q=text(url.searchParams.get('q'),100),location=text(url.searchParams.get('location'),100);const page=Math.max(1,Math.min(1000,Number(url.searchParams.get('page'))||1));
  if(provider==='adzuna'){if(!process.env.ADZUNA_APP_ID||!process.env.ADZUNA_APP_KEY)fail('Adzuna necesita sus credenciales en el servidor. Puedes buscar en los portales conectados.',503);const country=url.searchParams.get('country')||'es';if(!['es','gb','us','de','fr'].includes(country))fail('País no válido');const query=new URLSearchParams({app_id:process.env.ADZUNA_APP_ID,app_key:process.env.ADZUNA_APP_KEY,results_per_page:'20',what:q,where:location});let data;try{data=await remote(`https://api.adzuna.com/v1/api/jobs/${country}/search/${page}?${query}`);}catch{fail('No se pudo consultar Adzuna. Revisa configuración y cobertura del país.',502);}const jobs=(data.results||[]).map(j=>normalizeAdzuna(j,country));for(const j of jobs)catalog.set(j.id,j);json(res,{jobs,total:data.count||jobs.length,page,pageSize:20,sources:[{company:'Adzuna',status:'ok',count:jobs.length}],searchedAt:new Date().toISOString(),scope:'Resultados del agregador; descripciones resumidas'});return;}
  if(provider!=='boards')fail('Fuente no válida');const boards=sources();const outcomes=await Promise.allSettled(boards.map(board));let jobs=[],reports=[];outcomes.forEach((result,i)=>{if(result.status==='fulfilled'){jobs.push(...result.value.jobs);reports.push({company:boards[i].company,status:'ok',count:result.value.jobs.length,checkedAt:new Date(result.value.time).toISOString()});}else reports.push({company:boards[i].company,status:'error',count:0,message:'No se pudo consultar el portal. Inténtalo más tarde.'});});const unique=[...new Map(jobs.map(j=>[j.url||j.id,j])).values()];const filtered=filterOffers(unique,{q,location,company:url.searchParams.get('company')||'',country:url.searchParams.get('country')||'',salaryOnly:url.searchParams.get('salaryOnly')==='true'}).sort((a,b)=>(b.publishedAt||'').localeCompare(a.publishedAt||''));json(res,{jobs:filtered.slice((page-1)*20,page*20),total:filtered.length,page,pageSize:20,sources:reports,searchedAt:new Date().toISOString(),scope:'Solo ofertas de los portales conectados'});return;
 }
 if(url.pathname==='/offer'){const id=url.searchParams.get('id');let job=catalog.get(id);if(!job)fail('La oferta ya no está en la consulta. Vuelve a buscar antes de guardarla.',404);if(job.provider==='greenhouse'){try{const data=await remote(`https://boards-api.greenhouse.io/v1/boards/${encodeURIComponent(job.sourceBoard)}/jobs/${encodeURIComponent(job.externalId)}?pay_transparency=true`);const source=sources().find(s=>s.slug===job.sourceBoard&&s.provider==='greenhouse');if(!source)fail('Fuente desconectada',404);job=normalizeGreenhouse(data,source);if(data.pay_input_ranges?.length)job.salaryRanges=data.pay_input_ranges.map(r=>({min:r.min_cents/100,max:r.max_cents/100,currency:r.currency_type,interval:'Consultar periodicidad en la oferta',label:r.title,predicted:false}));job.salary=job.salaryRanges?.[0]||null;catalog.set(id,job);}catch(e){if(e.status===404)throw e;fail('No se pudo actualizar la oferta original. Vuelve a intentarlo.',502);}}json(res,job);return;}
 fail('Ruta no encontrada',404);
});
