import http from 'node:http';import {call,json,body,fail} from './common.mjs';import {allowedOrigin} from './origin.mjs';
const cookie=req=>req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('ts_session='))?.slice(11)||'';const counts=new Map();
export const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),p=url.pathname.replace(/^\/api/,'');const key=req.socket.remoteAddress,now=Date.now();let count=counts.get(key);if(!count||count.until<now)count={n:0,until:now+60000};count.n++;counts.set(key,count);if(count.n>150)fail('Demasiadas peticiones',429);if(req.method!=='GET'&&!allowedOrigin(req.headers.origin,process.env.PUBLIC_ORIGIN||'http://localhost:5173'))fail('Origen no permitido',403);const secure=(process.env.PUBLIC_ORIGIN||'').startsWith('https:')?'; Secure':'';
 if(['/auth/register','/auth/login'].includes(p)){if(req.method!=='POST')fail('Método no permitido',405);const result=await call('auth',p.replace('/auth',''),{method:'POST',body:JSON.stringify(await body(req)),headers:{'x-client-ip':key}});res.setHeader('Set-Cookie','ts_session='+result.token+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800'+secure);json(res,result.user);return;}
 const token=cookie(req),u=await call('auth','/me',{headers:{'x-session':token}}),headers={'x-session':token,'x-user':u.id,'x-account-type':u.profile.accountType||'','x-author-name':encodeURIComponent(u.profile.companyName||u.profile.name)};
 if(p==='/auth/me'){json(res,u);return;}
 if(p==='/auth/logout'&&req.method==='POST'){await call('auth','/logout',{method:'POST',headers});res.setHeader('Set-Cookie','ts_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'+secure);json(res,{ok:true});return;}
 if(p==='/auth/type'&&req.method==='POST'||p==='/auth/profile'&&req.method==='PATCH'){json(res,await call('auth',p.replace('/auth',''),{method:req.method,headers,body:JSON.stringify(await body(req))}));return;}
 if(!['junior','company'].includes(u.profile.accountType))fail('Selecciona Junior o Empresa para continuar',428);
 if(p==='/juniors'||p.startsWith('/juniors/')){if(req.method!=='GET')fail('Método no permitido',405);json(res,await call('auth',p+url.search,{headers}));return;}
 if(p==='/admin/overview'&&req.method==='GET'){json(res,await call('auth',p+url.search,{headers}));return;}
 if(p==='/offers'||p.startsWith('/offers/')||p==='/posts'||p.startsWith('/posts/')){const result=await call('community',p+url.search,{method:req.method,headers,...(['POST','PATCH'].includes(req.method)?{body:JSON.stringify(await body(req,800000))}:{})});if(['POST','PATCH','DELETE'].includes(req.method)){const type=(p.startsWith('/offers')?'offer':'contribution')+'_'+({POST:'created',PATCH:'updated',DELETE:'deleted'}[req.method]);await call('auth','/activity',{method:'POST',headers,body:JSON.stringify({type,title:result.title||'',id:result.id||p.split('/')[2]})});}json(res,result,req.method==='POST'?201:200);return;}
 fail('Ruta no encontrada',404);
 }catch(e){json(res,{error:e.status?e.message:'Servicio no disponible'},e.status||503);}}).listen(4100+Number(process.env.PORT_OFFSET||0),'127.0.0.1');
