import http from 'node:http';
import {call,json,body,fail} from './common.mjs';
import {allowedOrigin} from './origin.mjs';
function cookie(req){return req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('ts_session='))?.slice(11)||'';}
const counts=new Map();
export const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),p=url.pathname.replace(/^\/api/,'');const key=req.socket.remoteAddress,now=Date.now();let c=counts.get(key);if(!c||c.until<now)c={n:0,until:now+60000};c.n++;counts.set(key,c);if(c.n>150)fail('Demasiadas peticiones',429);if(req.method!=='GET'&&!allowedOrigin(req.headers.origin,process.env.PUBLIC_ORIGIN||'http://localhost:5173'))fail('Origen no permitido',403);
const secure=(process.env.PUBLIC_ORIGIN||'').startsWith('https:')?'; Secure':'';
if(['/auth/register','/auth/login'].includes(p)){if(req.method!=='POST')fail('Método no permitido',405);const r=await call('auth',p.replace('/auth',''),{method:'POST',body:JSON.stringify(await body(req)),headers:{'x-client-ip':key}});res.setHeader('Set-Cookie','ts_session='+r.token+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800'+secure);json(res,r.user);return;}
if(p==='/auth/linkedin/callback'){await call('auth','/linkedin/callback'+url.search);res.writeHead(302,{Location:'/account.html?connected=1'});res.end();return;}
const token=cookie(req),u=await call('auth','/me',{headers:{'x-session':token}}),headers={'x-session':token,'x-user':u.id};
if(!u.profile.resumeCompleted&&!u.profile.resumeSubmittedAt&&!p.startsWith('/auth/')&&p!=='/system')fail('Completa el análisis y la confirmación de tu CV para continuar.',428);
const track=async(type,details={})=>call('auth','/events',{method:'POST',headers,body:JSON.stringify({type,details})});
if(['/auth/cv/policy','/auth/cv/status'].includes(p)&&req.method==='GET'||p==='/auth/cv/analyze'&&req.method==='POST'||p==='/auth/cv/confirm'&&req.method==='POST'||p==='/auth/cv'&&req.method==='DELETE'){const result=await call('auth',p.replace('/auth',''),{method:req.method,headers,timeoutMs:330000,...(req.method==='POST'?{body:JSON.stringify(await body(req,p.endsWith('/analyze')?7100000:100000))}:{})});json(res,result,result.accepted?202:200);return;}
if(p==='/activity'&&req.method==='POST'){const b=await body(req);if(!['overview','jobs','company','activity','account','admin','discover','sources','examples','market'].includes(b.page))fail('Página no válida');if(b.page==='admin'&&u.profile.role!=='admin')fail('No autorizado',403);await track('page_view',{page:b.page});json(res,{ok:true});return;}
if(p==='/admin/overview'&&req.method==='GET'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);json(res,await call('auth','/admin/overview'+url.search,{headers}));return;}
if(p==='/auth/logout'){if(req.method!=='POST')fail('Método no permitido',405);await call('auth','/logout',{headers});res.setHeader('Set-Cookie','ts_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'+secure);json(res,{ok:true});return;}
if(p==='/auth/me'){json(res,u);return;}
if(p==='/admin/status'&&req.method==='GET'){json(res,await call('auth','/admin/status',{headers}));return;}
if(p==='/auth/profile'||p==='/auth/linkedin/start'){json(res,await call('auth',p.replace('/auth',''),{method:req.method,headers,...(req.method==='PATCH'?{body:JSON.stringify(await body(req))}:{})}));return;}
if(p==='/market/overview'&&req.method==='GET'){json(res,await call('discovery','/market'));return;}
if(p==='/discover/search'&&req.method==='GET'){const result=await call('discovery','/search'+url.search);await track('job_search',{title:url.searchParams.get('q')||'Todas las ofertas'});json(res,result);return;}
if(p==='/discover/offer'&&req.method==='GET'){json(res,await call('discovery','/offer'+url.search));return;}
if(p==='/companies/info'&&req.method==='GET'){json(res,await call('discovery','/company'+url.search));return;}
if(p==='/discover/sources'&&req.method==='GET'){json(res,await call('discovery','/sources'));return;}
if(p==='/discover/sources'&&req.method==='POST'||p.startsWith('/discover/sources/')&&req.method==='DELETE'){if(u.profile.role!=='admin')fail('Acceso exclusivo para administradores',403);const result=await call('discovery',p.replace('/discover',''),{method:req.method,...(req.method==='POST'?{body:JSON.stringify(await body(req))}:{})});await track('sources_updated');json(res,result);return;}
if(p==='/discover/import'&&req.method==='POST'){const input=await body(req);const offer=await call('discovery','/offer?id='+encodeURIComponent(input.id||''));const info=await call('discovery','/company?name='+encodeURIComponent(offer.company));const saved=await call('jobs','/jobs',{method:'POST',headers,body:JSON.stringify({...offer,externalKey:offer.id,applicants:null,vacancies:null,status:'saved',companyInfo:info})});if(!saved.alreadySaved){await track('offer_created',{title:saved.title,offerId:saved.id});if(u.profile.alerts){const a=await call('analysis','/analyze',{method:'POST',body:JSON.stringify({job:saved,profile:u.profile})});try{saved.notification=await call('mail','/send',{method:'POST',headers,body:JSON.stringify({to:u.email,job:saved,analysis:a})});}catch{saved.notification={status:'failed'};}await track('notification',{title:saved.title,offerId:saved.id,status:saved.notification.status});}}json(res,saved);return;}
if(p==='/system'){json(res,{linkedin:!!process.env.LINKEDIN_CLIENT_ID,email:!!(process.env.SMTP_HOST&&process.env.SMTP_FROM),services:['Autenticación','Ofertas','Análisis','Correo','Búsqueda'],mode:'Portales públicos conectados y ofertas aportadas por el usuario'});return;}
if(p==='/mail/history'){json(res,await call('mail','/history',{headers}));return;}
if(/^\/jobs\/[a-z0-9-]+\/(analysis|notify)$/.test(p)){const job=await call('jobs',p.split('/').slice(0,3).join('/'),{headers});const analysis=await call('analysis','/analyze',{method:'POST',body:JSON.stringify({job,profile:u.profile})});if(p.endsWith('/analysis')){await track('analysis_viewed',{title:job.title,offerId:job.id});json(res,analysis);return;}if(req.method!=='POST')fail('Método no permitido',405);const delivery=await call('mail','/send',{method:'POST',headers,body:JSON.stringify({to:u.email,job,analysis})});await track('notification',{title:job.title,offerId:job.id,status:delivery.status});json(res,delivery);return;}
if(p==='/jobs'||/^\/jobs\/[a-z0-9-]+$/.test(p)){const r=await call('jobs',p,{method:req.method,headers,...(['POST','PATCH'].includes(req.method)?{body:JSON.stringify(await body(req))}:{})});if(req.method==='POST'&&u.profile.alerts){const analysis=await call('analysis','/analyze',{method:'POST',body:JSON.stringify({job:r,profile:u.profile})});try{r.notification=await call('mail','/send',{method:'POST',headers,body:JSON.stringify({to:u.email,job:r,analysis})});}catch{r.notification={status:'failed'};}}if(['POST','PATCH','DELETE'].includes(req.method)){await track(({POST:'offer_created',PATCH:'offer_updated',DELETE:'offer_deleted'})[req.method],{title:r.title,offerId:r.id||p.split('/')[2],status:r.status});if(r.notification)await track('notification',{title:r.title,offerId:r.id,status:r.notification.status});}json(res,r);return;}fail('Ruta no encontrada',404);
}catch(e){json(res,{error:e.status?e.message:'Servicio no disponible'},e.status||503);}}).listen(4100+Number(process.env.PORT_OFFSET||0),'127.0.0.1',()=>console.log('API REST lista en 4100'));
