import {randomUUID} from 'node:crypto';
import {text,fail} from './common.mjs';
export const publicationFields=['nombre','presentación','descripción','estudios y titulaciones','formación profesional','idiomas','competencias','prácticas','qué puedes aportar','ubicación','disponibilidad','portfolio'];
export const publicationConsentVersion='junior-profile-v1';
export function initializeModeration(db){db.exec(`
 CREATE TABLE IF NOT EXISTS restrictions(user TEXT PRIMARY KEY,mode TEXT NOT NULL,reason TEXT NOT NULL,until TEXT,created_at TEXT NOT NULL,actor TEXT NOT NULL,cleared_at TEXT);
 CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,reporter TEXT NOT NULL,target_user TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,context TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,resolved_at TEXT,resolved_by TEXT,resolution TEXT);
 CREATE TABLE IF NOT EXISTS moderation_actions(id TEXT PRIMARY KEY,actor TEXT NOT NULL,target_user TEXT,report_id TEXT,action TEXT NOT NULL,details TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS reports_status ON reports(status,created_at);
 CREATE TABLE IF NOT EXISTS profile_consents(id TEXT PRIMARY KEY,user TEXT NOT NULL,version TEXT NOT NULL,accepted_at TEXT NOT NULL);
 `);}
export function restriction(db,id){const r=db.prepare('SELECT * FROM restrictions WHERE user=?').get(id);if(!r||r.cleared_at)return {active:false};const active=r.mode==='permanent'||Date.parse(r.until)>Date.now();return {active,mode:r.mode,reason:r.reason,until:r.until,createdAt:r.created_at,expired:!active};}
export function assertCanWrite(db,id){const r=restriction(db,id);if(r.active)fail('No puedes publicar contenido: '+r.reason+(r.until?' · Hasta '+r.until:' · Bloqueo permanente'),403);}
function audit(db,actor,target,report,action,details){db.prepare('INSERT INTO moderation_actions VALUES(?,?,?,?,?,?,?)').run(randomUUID(),actor,target||null,report||null,action,JSON.stringify(details),new Date().toISOString());}
export function submitReport(db,reporter,input){const reason=text(input.reason,1000),context=text(input.context,4000),targetType=input.targetType,targetId=text(input.targetId,100),targetUser=text(input.targetUser,100);if(!['user','post'].includes(targetType)||!targetId||!targetUser||reason.length<5)fail('Selecciona el contenido e indica un motivo de al menos 5 caracteres');if(targetUser===reporter)fail('No puedes denunciarte a ti mismo');if(!db.prepare('SELECT id FROM users WHERE id=?').get(targetUser))fail('Usuario no encontrado',404);const recent=db.prepare('SELECT COUNT(*) AS n FROM reports WHERE reporter=? AND created_at>?').get(reporter,new Date(Date.now()-86400000).toISOString()).n;if(recent>=10)fail('Máximo de diez denuncias por día',429);if(db.prepare("SELECT id FROM reports WHERE reporter=? AND target_type=? AND target_id=? AND status='open'").get(reporter,targetType,targetId))fail('Ya tienes una denuncia abierta sobre este contenido',409);const id=randomUUID(),now=new Date().toISOString();db.prepare('INSERT INTO reports(id,reporter,target_user,target_type,target_id,reason,context,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,reporter,targetUser,targetType,targetId,reason,context,'open',now);audit(db,reporter,targetUser,id,'report_created',{reason,context,targetType,targetId});return {id,status:'open',createdAt:now};}
export function listReports(db,params){const page=Math.max(1,Number.parseInt(params.get('page'))||1),status=['open','resolved','dismissed'].includes(params.get('status'))?params.get('status'):'';const where=status?' WHERE r.status=?':'';const args=status?[status]:[];const total=db.prepare('SELECT COUNT(*) AS n FROM reports r'+where).get(...args).n;const items=db.prepare(`SELECT r.*,json_extract(u.profile,'$.name') AS targetName,json_extract(a.profile,'$.name') AS reporterName FROM reports r JOIN users u ON u.id=r.target_user JOIN users a ON a.id=r.reporter${where} ORDER BY r.created_at DESC LIMIT 20 OFFSET ?`).all(...args,(page-1)*20).map(r=>({...r,restriction:restriction(db,r.target_user)}));return {items,total,page,pageSize:20};}
export function setRestriction(db,actor,id,input){const row=db.prepare('SELECT profile FROM users WHERE id=?').get(id);if(!row)fail('Usuario no encontrado',404);if(id===actor||JSON.parse(row.profile).role==='admin')fail('No se bloquean administradores desde esta pantalla',403);const reason=text(input.reason,1000);if(reason.length<3)fail('Indica el motivo del bloqueo');const mode=input.mode;let until=null;if(mode==='temporary'){const date=new Date(input.until);if(!Number.isFinite(date.getTime())||date.getTime()<=Date.now())fail('Indica una fecha de fin futura');until=date.toISOString();}else if(mode!=='permanent')fail('Selecciona temporal o permanente');const now=new Date().toISOString();db.prepare('INSERT INTO restrictions VALUES(?,?,?,?,?,?,NULL) ON CONFLICT(user) DO UPDATE SET mode=excluded.mode,reason=excluded.reason,until=excluded.until,created_at=excluded.created_at,actor=excluded.actor,cleared_at=NULL').run(id,mode,reason,until,now,actor);audit(db,actor,id,null,'user_blocked',{mode,reason,until});return restriction(db,id);}
export function clearRestriction(db,actor,id,input){if(!db.prepare('SELECT id FROM users WHERE id=?').get(id))fail('Usuario no encontrado',404);const reason=text(input.reason,1000);if(reason.length<3)fail('Indica el motivo del desbloqueo');db.prepare('UPDATE restrictions SET cleared_at=? WHERE user=?').run(new Date().toISOString(),id);audit(db,actor,id,null,'user_unblocked',{reason});return restriction(db,id);}
export function resolveReport(db,actor,id,input){const row=db.prepare('SELECT * FROM reports WHERE id=?').get(id);if(!row)fail('Denuncia no encontrada',404);if(!['resolved','dismissed'].includes(input.status)||text(input.resolution,2000).length<3)fail('Indica resolución y motivo');if(row.status!=='open')fail('La denuncia ya está resuelta',409);db.prepare('UPDATE reports SET status=?,resolved_at=?,resolved_by=?,resolution=? WHERE id=?').run(input.status,new Date().toISOString(),actor,text(input.resolution,2000),id);audit(db,actor,row.target_user,id,'report_resolved',{status:input.status,resolution:text(input.resolution,2000)});return {ok:true};}
