// Synthetic examples only. These are not real members, employers or job openings.
const locations=[['Madrid','España'],['Lisboa','Portugal'],['Valencia','España'],['Barcelona','España'],['Oporto','Portugal'],['Berlín','Alemania'],['Sevilla','España'],['París','Francia'],['Málaga','España'],['Ámsterdam','Países Bajos']];
const tracks=[['FP Desarrollo de Aplicaciones Web','React, CSS, Git','Me gusta convertir ideas en interfaces accesibles. Mi proyecto final es una biblioteca de componentes.'],['Grado en Estadística','Python, SQL, visualización','Exploro cómo contar historias con datos. Busco un equipo con el que seguir aprendiendo.'],['FP Desarrollo de Aplicaciones Multiplataforma','Java, JavaScript, Git','Construyo herramientas pequeñas que resuelven problemas cotidianos.'],['Grado en Diseño','Figma, UX, prototipado','Investigo cómo simplificar productos digitales y pruebo prototipos con usuarios.'],['FP Administración de Sistemas','Linux, redes, Docker','Aprendo a automatizar tareas y a mantener servicios fáciles de entender.'],['Grado en Ingeniería Informática','Node.js, SQL, APIs','Desarrollo APIs pequeñas y documento las decisiones de cada proyecto.'],['Grado en Matemáticas','Python, modelos, análisis','Me interesan los modelos interpretables y explicar sus límites con claridad.'],['FP Animaciones 3D y Videojuegos','Unity, C#, Blender','Diseño experiencias interactivas y prototipos de juegos con mecánicas sencillas.'],['Grado en Marketing','Analítica, contenido, SEO','Combino investigación y contenidos para comunicar proyectos con claridad.'],['Grado en Ingeniería de Telecomunicaciones','Redes, Python, seguridad','Exploro redes y seguridad con laboratorios aislados y documentación reproducible.'],['FP Desarrollo de Aplicaciones Web','Vue, JavaScript, pruebas','Quiero construir aplicaciones útiles y aprender a probarlas desde el principio.'],['Grado en Comunicación Audiovisual','Edición, diseño, narrativa','Me interesa explicar tecnología con historias, vídeo y diseño visual.'],['FP Desarrollo de Aplicaciones Multiplataforma','Kotlin, Android, SQLite','Creo prototipos móviles que funcionan sin conexión y cuidan la accesibilidad.'],['Grado en Ingeniería Informática','TypeScript, React, accesibilidad','Construyo componentes reutilizables y reviso la experiencia con teclado.'],['FP Administración de Sistemas','Cloud, Linux, automatización','Me gusta convertir procesos manuales en scripts claros, seguros y repetibles.']];
export const people=['Alex Vega','Cris Marín','Dani Sol','Noa Ríos','Leo Prado','Ari Luna','Sam Valle','Iris Roble','Hugo Faro','Lara Monte','Teo Alba','Vera Nube','Nil Costa','Ada Río','Max Olmo'].map((name,i)=>({id:i+1,name,studies:tracks[i][0],skills:tracks[i][1],text:tracks[i][2],location:locations[i%locations.length][0],country:locations[i%locations.length][1]}));
const companyNames=['Lumen Studio','Nébula Labs','Bosque Digital','Brisa Software','Órbita UX','Prisma Datos','Raíz Cloud','Faro Interfaces','Marea Apps','Nido Tecnología','Horizonte Web','Cauce Analytics','Trama Digital','Pétalo Systems','Atlas Creativo','Aurora Código','Bambú Dev','Cometa Mobile','Duna Studio','EcoPixel','Folio Labs','Girasol Tech','Hiedra Software','Isla Datos','Jardín Digital','Kiwi Interfaces','Ladera Cloud','Musgo Apps','Norte UX','Onda Código','Pino Analytics','Quilla Dev','Rama Mobile','Sendero Studio','Tilia Tech','Umbral Systems','Vértice Creativo','Wabi Web','Xilo Labs','Yedra Digital','Zafiro Apps','Alameda Software','Bahía UX','Cobalto Datos','Delta Interfaces','Estela Cloud','Fresno Dev','Granate Mobile','Huella Studio','Índigo Tecnología'];
const industries=['Productos web accesibles','Herramientas de análisis de datos','Aplicaciones educativas','Diseño de experiencias digitales','Servicios cloud para equipos pequeños','Aplicaciones móviles','Tecnología ambiental','Herramientas de colaboración','Visualización científica','Automatización de procesos'];
export const companies=companyNames.map((name,i)=>({id:i+1,name,business:industries[i%industries.length],location:locations[i%locations.length][0],country:locations[i%locations.length][1],employees:8+(i*7)%113,description:`Empresa ficticia de ${industries[i%industries.length].toLowerCase()}. Este ejemplo propone aprendizaje acompañado, revisión del trabajo y colaboración entre perfiles técnicos y creativos.`,office:`Sede de ejemplo en ${locations[i%locations.length][0]}`}));
const roles=[['Frontend junior · React','React, CSS, accesibilidad','FP DAW, DAM o estudios relacionados','Construye interfaces accesibles con acompañamiento y revisiones de código. Un espacio para aprender y aportar desde el primer día.'],['Analista de datos en formación','SQL, Python, visualización','Estudios de datos, matemáticas o informática','Transforma datos en preguntas útiles y crea dashboards con un equipo de investigación.'],['Desarrollo web sostenible','JavaScript, HTML, Git','FP DAW o formación equivalente','Ayuda a crear experiencias web ligeras, mide su rendimiento y colabora en pequeñas mejoras.'],['Diseño UX/UI junior','Figma, investigación, prototipos','Diseño, comunicación o formación relacionada','Colabora en entrevistas de ejemplo, mapas de experiencia y prototipos que se puedan probar.'],['Soporte cloud en formación','Linux, redes, Docker','FP ASIR o estudios relacionados','Aprende a mantener servicios, documentar incidencias y automatizar tareas en entornos de práctica.'],['Desarrollo backend junior','Node.js, SQL, APIs','FP DAM, DAW o ingeniería informática','Construye APIs pequeñas, revisa su autorización y participa en pruebas y documentación.'],['QA y automatización junior','Pruebas, JavaScript, Git','Formación técnica y proyectos de pruebas','Diseña casos de prueba y aprende a detectar errores antes de que lleguen al usuario.'],['Desarrollo Android junior','Kotlin, Android, SQLite','FP DAM o formación en aplicaciones móviles','Colabora en pantallas móviles, almacenamiento sin conexión y mejoras de accesibilidad.'],['Contenido digital y analítica','Comunicación, SEO, analítica','Marketing, comunicación o formación equivalente','Explica productos digitales con contenidos claros y analiza resultados de campañas de ejemplo.'],['Seguridad técnica en formación','Redes, Linux, Python','FP ASIR, telecomunicaciones o informática','Documenta controles y practica revisiones de seguridad en laboratorios autorizados y aislados.']];
export const initialOffers=companies.map((c,i)=>({id:c.id,companyId:c.id,title:roles[i%roles.length][0],company:c.name,country:c.country,location:c.location,mode:['Híbrido','Remoto','Presencial'][i%3],salary:`${(20+i%9).toLocaleString('es-ES')}.000–${(24+i%9).toLocaleString('es-ES')}.000 € / año · Ficticio`,skills:roles[i%roles.length][1],degree:roles[i%roles.length][2],description:roles[i%roles.length][3],status:'published'}));
const topics=[
 ['Un pequeño proyecto. Un gran primer paso.','He construido una biblioteca de componentes en React para practicar formularios, pestañas y navegación con teclado.','React · Accesibilidad'],
 ['¿Qué nos cuentan los datos sobre una ciudad?','Un dashboard con datos sintéticos de movilidad me ha ayudado a distinguir una tendencia de una anécdota.','Python · Datos'],
 ['Aprender juntos también es aportar.','He preparado una guía de Git para quienes empiezan, con ramas y revisiones de cambios pequeños.','Git · Comunidad'],
 ['Mi primer prototipo de una biblioteca digital','Organicé una búsqueda, favoritos y fichas de lectura en un prototipo que se puede recorrer antes de escribir código.','UX · Figma'],
 ['Un laboratorio Linux que puedo reconstruir','Documenté una máquina de prácticas para repetir la instalación y entender cada servicio que arranca.','Linux · Sistemas'],
 ['Diseñar una API empieza por sus preguntas','Antes de crear endpoints escribí qué necesita consultar cada usuario y qué acciones debe tener permitidas.','APIs · Node.js'],
 ['Modelos sencillos, explicaciones claras','Comparé dos modelos sobre datos inventados y descubrí que explicar el error es tan útil como mostrar la predicción.','Matemáticas · Modelos'],
 ['Un minijuego para practicar decisiones de diseño','Probé un nivel corto en Unity y ajusté los controles después de observar dónde se atascaba quien lo jugaba.','Unity · Prototipos'],
 ['Medir contenido sin perder de vista a las personas','Creé una campaña ficticia para comparar títulos y aprender a interpretar métricas sin sacar conclusiones precipitadas.','Contenido · Analítica'],
 ['Entender una red dibujándola primero','Un esquema de laboratorio me permitió explicar cómo viajan las peticiones y dónde debe limitarse el acceso.','Redes · Seguridad'],
 ['De un formulario vacío a una experiencia útil','Practiqué mensajes de error que explican cómo corregir un campo y se pueden encontrar con lectores de pantalla.','Formularios · Accesibilidad'],
 ['Contar una idea técnica en noventa segundos','Escribí el guion de un vídeo de ejemplo para explicar un proyecto sin llenar la pantalla de términos nuevos.','Narrativa · Comunicación'],
 ['Una app de notas que funciona sin conexión','Construí un prototipo Android con almacenamiento local y revisé cómo mostrar el estado de guardado.','Kotlin · Android'],
 ['TypeScript me obligó a hacer mejores preguntas','Definir los tipos de un componente hizo visibles estados que no había considerado en el primer boceto.','TypeScript · React'],
 ['Mi primer script de automatización documentado','Automaticé una tarea de laboratorio y añadí instrucciones para entenderla y repetirla con datos ficticios.','Automatización · Cloud'],
 ['Una paleta de colores que sí se puede leer','Comparé combinaciones de color y revisé el contraste antes de aplicar la paleta a un diseño de muestra.','Diseño · Contraste'],
 ['SQL: de tablas pequeñas a preguntas útiles','Preparé una base sintética de pedidos y practiqué consultas que responden una sola pregunta cada vez.','SQL · Datos'],
 ['Revisar código sin convertirlo en un examen','Ensayé una revisión con comentarios concretos sobre el comportamiento y propuestas fáciles de comprobar.','Colaboración · Git'],
 ['Por qué mi prototipo necesitaba un estado vacío','Diseñé una pantalla sin resultados para explicar qué había ocurrido y ofrecer un siguiente paso útil.','UX · Producto'],
 ['Docker explicado con una aplicación pequeña','Usé un servicio de prueba para entender qué entra en una imagen y qué información debe mantenerse fuera.','Docker · Sistemas'],
 ['Un dashboard que muestra también sus límites','Añadí fechas y notas sobre datos incompletos para evitar que una gráfica de práctica pareciera una certeza.','Dashboards · Investigación'],
 ['Pruebas pequeñas para errores importantes','Elegí casos que cubren permisos y entradas inesperadas en lugar de comprobar detalles internos del código.','QA · Pruebas'],
 ['Una landing ligera para un proyecto educativo','Reduje recursos y simplifiqué la navegación de una web ficticia para que cargara bien en conexiones lentas.','Web · Rendimiento'],
 ['Preguntar antes de dibujar pantallas','Preparé preguntas abiertas de investigación y separé lo observado de mis suposiciones sobre el producto.','Investigación · UX'],
 ['Mi cuaderno de aprendizaje de JavaScript','Reuní ejercicios sobre funciones y objetos, con explicaciones de los errores que cometí al resolverlos.','JavaScript · Aprendizaje'],
 ['Versionar un proyecto de datos también importa','Guardé consultas y transformaciones junto a una explicación del conjunto sintético usado en el ejercicio.','Datos · Reproducibilidad'],
 ['Una interfaz que no depende solo del ratón','Recorrí un prototipo con teclado y cambié el orden del foco para que coincidiera con las acciones esperadas.','Accesibilidad · React'],
 ['Probar una idea antes de ampliarla','Construí una versión mínima de un organizador de tareas y anoté qué preguntas seguían sin respuesta.','Prototipos · Producto'],
 ['Primeros pasos con una integración continua','Configuré una comprobación automática de un proyecto de laboratorio para entender cómo detectar cambios que fallan.','CI · Git'],
 ['Datos sintéticos para aprender con privacidad','Diseñé registros inventados que conservan casos interesantes sin copiar información personal de otras personas.','Privacidad · Datos'],
 ['Escribir documentación que acompaña al código','Separé instalación, uso y decisiones de diseño para que alguien nuevo pueda recorrer el proyecto con contexto.','Documentación · Comunidad'],
 ['Un buscador pequeño, muchos estados posibles','Probé una búsqueda sin resultados, con filtros y con entradas vacías para mejorar sus mensajes.','Búsqueda · Frontend'],
 ['Lo que aprendí al dibujar un modelo de datos','Representé las relaciones de una aplicación ficticia y encontré información que estaba duplicando sin necesidad.','Bases de datos · Diseño'],
 ['Un portfolio que explica el proceso','Añadí a cada proyecto qué problema intentaba resolver, qué probé y qué cambiaría en una nueva versión.','Portfolio · Carrera'],
 ['Investigar sin presentar hipótesis como hechos','Usé un ejercicio sencillo para practicar cómo separar preguntas, resultados y explicaciones posibles.','Investigación · Método'],
 ['Una aplicación móvil con textos más claros','Reescribí acciones y errores de un prototipo para que su propósito se entendiera sin instrucciones externas.','Android · UX'],
 ['Un mapa de componentes antes del diseño final','Organicé botones, campos y tarjetas en una estructura que facilita mantener consistencia entre pantallas.','Componentes · Diseño'],
 ['Entender un error leyendo la petición completa','Seguí una petición de prueba desde el navegador hasta el servicio para localizar dónde cambiaba su resultado.','APIs · Depuración'],
 ['Aprender seguridad con ejemplos aislados','Preparé un laboratorio sin datos reales para practicar permisos y comprobar rechazos de acciones no autorizadas.','Seguridad · Aprendizaje'],
 ['Un calendario de contenido para una comunidad ficticia','Organicé piezas cortas sobre proyectos y aprendizaje, con objetivos claros para cada publicación de ejemplo.','Comunicación · Contenido'],
 ['Qué cambia cuando una gráfica tiene escala','Comparé dos representaciones del mismo conjunto inventado para ver cómo las decisiones visuales afectan la lectura.','Visualización · Estadística'],
 ['Una lista de tareas accesible desde cero','Añadí etiquetas, foco visible y mensajes de estado a un ejercicio de tareas construido con componentes simples.','Frontend · Accesibilidad'],
 ['Organizar una práctica en equipo','Dividimos un proyecto de muestra en tareas pequeñas y explicamos qué significaba terminar cada una.','Equipo · Proyectos'],
 ['La diferencia entre guardar y sincronizar','Usé una app ficticia para mostrar qué datos existen solo en una pestaña y cuáles necesitarían un servidor.','Arquitectura · Web'],
 ['Diseñar una encuesta que no sugiera la respuesta','Revisé preguntas de ejemplo para evitar que mis preferencias influyeran en lo que otros podrían contestar.','UX · Investigación'],
 ['Un ejercicio de caché con resultados medibles','Medí peticiones de un servicio de laboratorio antes y después de una mejora, documentando las condiciones de prueba.','Rendimiento · Backend'],
 ['Aprender Kotlin construyendo una pantalla sencilla','Practiqué estados y validación con un formulario móvil que explica por qué un dato necesita corregirse.','Kotlin · Formación'],
 ['Una guía para presentar tu primer proyecto','Preparé un esquema para explicar propósito, decisiones, pruebas y siguientes pasos sin ocultar lo que falta.','Carrera · Comunicación'],
 ['Por qué la incertidumbre merece espacio en el diseño','Añadí notas y rangos a un prototipo de análisis para que una estimación no se confundiera con un resultado seguro.','Producto · Datos'],
 ['Compartir lo aprendido sin aparentar saberlo todo','Organicé notas de una práctica con fuentes, errores y preguntas pendientes para que otras personas puedan seguir investigando.','Comunidad · Aprendizaje']
];
export const initialPosts=topics.map(([title,intro,tags],i)=>({id:i+1,title,name:people[i%people.length].name,kind:['Proyecto','Investigación','Aportación'][i%3],text:`${intro}\n\nEn este ejemplo educativo definí un objetivo pequeño, preparé un prototipo y registré las decisiones para poder revisarlas. La práctica usa contenidos inventados y no representa un proyecto o una publicación de una persona real.\n\nMi siguiente paso sería contrastar el resultado, ampliar las pruebas y documentar qué limitaciones permanecen. Las métricas y reacciones que aparecen en esta demo son ilustrativas.`,tags,icon:['code','research','people'][i%3],likes:4+(i*7)%43}));
