import React,{useEffect,useState,useRef} from 'react';
import {api,Modal,Loading} from './shared.jsx';
import {publicFields} from './social.jsx';
export const states={contacted:'Conversación iniciada',submitted:'Candidatura enviada',reviewing:'En revisión',shortlisted:'Preseleccionada',rejected:'No seleccionada',withdrawn:'Retirada'};
const fields={headline:'Presentación',description:'Sobre ti',studies:'Estudios',vocationalTraining:'Formación profesional',languages:'Idiomas',skills:'Competencias',internships:'Prácticas',contribution:'Aportación',location:'Ubicación',availability:'Disponibilidad',portfolio:'Portfolio'};
export function SharedProfile({profile}){return profile?<section className="panel"><h3>Perfil compartido al presentar la candidatura</h3><p>{profile.name}</p><dl className="js-facts">{Object.entries(fields).map(([key,label])=>profile[key]&&<div key={key}><dt>{label}</dt><dd className="pre-text">{profile[key]}</dd></div>)}</dl><small>Información declarada por el candidato, sin verificar.</small></section>:<p>No hay perfil compartido. Al retirar una candidatura se elimina su copia de esta conversación.</p>;}
export function HiringActions({offer,user,onOpen,onChanged,onCandidates}){
 const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false);
 const junior=user?.profile.accountType==='junior';
 useEffect(()=>{let active=true;if(junior)api('/offers/'+offer.id+'/application').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[offer.id,junior]);
 if(!user)return null;
 if(!junior)return offer.ownerId===user.id?<button className="primary" onClick={()=>onCandidates(offer)}>Ver candidatos y mensajes</button>:null;
 async function act(path,method,body){setBusy(true);setError('');try{const r=await api('/offers/'+offer.id+path,method,body);if(path==='/decision'){setData(d=>({...d,discarded:r.discarded}));onChanged?.();}else{setData(d=>({...d,application:r}));setConsent(false);onOpen(r.id);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 const applied=data?.application&&!['contacted','withdrawn'].includes(data.application.status),blocked=user.restriction?.active;
 return <section className="hiring-actions panel"><h3>Tu siguiente paso</h3><p>La candidatura y los mensajes solo los ven tu cuenta y la empresa de esta oferta.</p>{data?.application&&<p role="status">{states[data.application.status]}</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="contact-actions">{offer.status==='published'&&!applied&&<button className="primary" disabled={busy||blocked||!data} onClick={()=>setConsent(true)}>Presentar mi candidatura</button>}{data?.application?<button className="secondary" onClick={()=>onOpen(data.application.id)}>Abrir conversación</button>:offer.status==='published'&&<button className="secondary" disabled={busy||blocked||!data} onClick={()=>act('/conversation','POST',{})}>Escribir a la empresa</button>}{offer.status==='published'&&<button className="secondary" disabled={busy||!data} onClick={()=>act('/decision',data?.discarded?'DELETE':'PUT',{})}>{data?.discarded?'Recuperar oportunidad':'Descartar para mí'}</button>}</div><small>Al escribir compartes tu nombre y tu mensaje. Descartar solo afecta a tu lista, no cierra la oferta ni retira una candidatura.</small>{consent&&<Modal title="Revisa lo que compartirás" onClose={()=>setConsent(false)}><p>Compartirás con {offer.companyName}: {publicFields}. Esto permite enviar tu perfil aunque esté oculto en el directorio. No se envían tu correo de acceso, contraseña ni currículum anterior.</p><SharedProfile profile={user.profile}/><form onSubmit={e=>{e.preventDefault();act('/application','POST',{acceptedSharing:true,sharingVersion:data.sharingVersion});}}><label className="check-label"><input type="checkbox" required/>Acepto compartir mi perfil profesional con la empresa de esta oferta para esta candidatura.</label><p>Puedes retirarla después. Tus mensajes permanecerán en la conversación privada.</p>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy||blocked}>Confirmar candidatura</button></form></Modal>}</section>;
}
export function Conversation({id,user,onChanged}){
 const[application,setApplication]=useState(null),[messages,setMessages]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[hasMore,setHasMore]=useState(false),cursor=useRef(null),refreshing=useRef(false);
 useEffect(()=>{let active=true;cursor.current=null;setMessages([]);setApplication(null);setError('');async function refresh(){if(refreshing.current)return;refreshing.current=true;try{const a=await api('/applications/'+id),m=await api('/applications/'+id+'/messages'+(cursor.current?'?after='+encodeURIComponent(cursor.current):''));if(active){setApplication(a);setMessages(old=>{const seen=new Set(old.map(x=>x.id));return [...old,...m.items.filter(x=>!seen.has(x.id))];});cursor.current=m.nextCursor;setHasMore(m.hasMore);}}catch(e){if(active)setError(e.message);}finally{refreshing.current=false;}}refresh();const timer=setInterval(refresh,10000);return()=>{active=false;clearInterval(timer);};},[id]);
 async function mutate(method,data){setBusy(true);setError('');try{setApplication(await api('/applications/'+id,method,data));onChanged?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function more(){try{const m=await api('/applications/'+id+'/messages'+(cursor.current?'?after='+encodeURIComponent(cursor.current):''));setMessages(old=>{const seen=new Set(old.map(x=>x.id));return [...old,...m.items.filter(x=>!seen.has(x.id))];});cursor.current=m.nextCursor;setHasMore(m.hasMore);}catch(e){setError(e.message);}}
 return <section className="conversation">{error&&<p className="error" role="alert">{error}</p>}{!application?<Loading/>:<><h2>{application.offerTitle}</h2><p>{application.juniorName} · {application.companyName}</p><p className="pill">{states[application.status]}</p><small>Oferta: {application.offerStatus==='published'?'abierta':application.offerStatus==='deleted'?'eliminada':'cerrada o privada'}. Una conversación existente sigue disponible para sus participantes.</small>{application.participant==='company'?<><SharedProfile profile={application.profile}/>{!['contacted','withdrawn'].includes(application.status)&&<label>Estado de la candidatura<select value={application.status} disabled={busy||user.restriction?.active||user.profile.accountType!=='company'} onChange={e=>mutate('PATCH',{status:e.target.value})}><option value="submitted" disabled>Enviada</option>{['reviewing','shortlisted','rejected'].map(s=><option key={s} value={s}>{states[s]}</option>)}</select></label>}</>:!['contacted','withdrawn'].includes(application.status)&&<button className="secondary danger" disabled={busy} onClick={()=>mutate('DELETE')}>Retirar candidatura y perfil compartido</button>}<h3>Mensajes privados</h3><div className="private-messages" aria-label="Conversación privada">{messages.length?messages.map(m=><article key={m.id} className={'private-message '+(m.senderId===user.id?'mine':'')}><b>{m.senderName}</b><small>{new Date(m.createdAt).toLocaleString('es-ES')}</small><p className="pre-text">{m.content}</p></article>):<p>Todavía no hay mensajes. Puedes empezar por una pregunta sobre la oferta.</p>}</div>{hasMore&&<button className="secondary" onClick={more}>Cargar siguientes mensajes</button>}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,content=new FormData(form).get('content');setBusy(true);setError('');try{const m=await api('/applications/'+id+'/messages','POST',{content});setMessages(old=>[...old,m]);form.reset();onChanged?.();}catch(e){setError(e.message);}finally{setBusy(false);}}}><label>Tu mensaje<textarea name="content" required maxLength={4000} rows={3} disabled={user.restriction?.active}/></label><small>No compartas contraseñas, documentos sensibles o información privada de terceros.</small><button className="primary" disabled={busy||user.restriction?.active||user.profile.accountType!==application.participant}>Enviar mensaje</button></form></>}</section>;
}
export function HiringInbox({user,initialId,offerId}){
 const[data,setData]=useState(null),[page,setPage]=useState(1),[selected,setSelected]=useState(initialId||null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{setSelected(initialId||null);},[initialId]);
 useEffect(()=>{let active=true;async function load(){try{const d=await api((offerId?'/offers/'+offerId+'/candidates':'/applications')+'?page='+page);if(active){setData(d);setError('');}}catch(e){if(active)setError(e.message);}}load();const timer=setInterval(load,20000);return()=>{active=false;clearInterval(timer);};},[user.id,user.profile.accountType,offerId,page,revision]);
 return <><div className="page-heading"><div><span className="eyebrow">CONEXIONES CON UN SIGUIENTE PASO</span><h1>{user.profile.accountType==='company'?'Candidatos y mensajes':'Mis candidaturas y mensajes'}</h1><p>Conversaciones privadas con los participantes de cada oportunidad.</p></div></div>{error&&<p className="error" role="alert">{error}</p>}<div className="hiring-inbox"><aside className="panel thread-list">{!data?<Loading/>:data.items.length?data.items.map(a=><button key={a.id} className={'thread-choice '+(selected===a.id?'selected':'')} onClick={()=>setSelected(a.id)}><b>{a.offerTitle}</b><span>{user.profile.accountType==='company'?a.juniorName:a.companyName}</span><small>{states[a.status]} · {a.messageCount} mensajes</small><small>{a.appliedAt?'Candidatura: ':'Inicio: '}{new Date(a.appliedAt||a.createdAt).toLocaleDateString('es-ES')}</small></button>):<p>{user.profile.accountType==='company'?'Los candidatos aparecerán cuando un junior se presente o escriba sobre una de tus ofertas.':'Abre una oferta para presentarte o escribir a la empresa.'}</p>}{data?.total>20&&<div className="contact-actions"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{page}</span><button disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div>}</aside><main className="panel">{selected?<Conversation key={selected} id={selected} user={user} onChanged={()=>setRevision(r=>r+1)}/>:<p>Selecciona una conversación para ver el perfil compartido, el estado y los mensajes.</p>}</main></div></>;
}
