import {ResumeStatus} from './resume-status.jsx';
import React,{useState,useEffect} from 'react';
import {Radar,LayoutDashboard,BriefcaseBusiness,Building2,Mail,Settings2,LogOut,ArrowUpRight,ShieldCheck,LoaderCircle,Check,X,Blocks as LayersIcon} from 'lucide-react';
import './style.css';
import './remodel.css';
export async function api(path,method='GET',data){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const b=await r.json();if(!r.ok)throw new Error(b.error||'No se pudo completar la acción');return b;}
export function useUser(){const[user,setUser]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{api('/auth/me').then(setUser).catch(()=>{}).finally(()=>setLoading(false));},[]);return{user,setUser,loading};}
export function Brand(){return <a className="brand" href="/"><span className="brandmark"><Radar size={25}/></span>talent<span>scope</span><small>BETA</small></a>;}
export function Notice({message,onClose}){return message&&<div className="toast" role="status">{message}<button aria-label="Cerrar aviso" onClick={onClose}><X size={16}/></button></div>;}
export function Shell({user,active,onNav,children,account=false,admin=false}){useEffect(()=>{api('/activity','POST',{page:admin?'admin':account?'account':active||'overview'}).catch(()=>{});},[user.id,active,account,admin]);const nav=[['discover',BriefcaseBusiness,'Buscar empleo'],['market',LayoutDashboard,'Mercado laboral'],['sources',Settings2,'Fuentes de empleo'],['examples',LayersIcon,'Ejemplos React'],['overview',LayoutDashboard,'Mi panel'],['jobs',BriefcaseBusiness,'Mis ofertas'],['company',Building2,'Empresas'],['activity',Mail,'Notificaciones']];return <div className="shell"><aside className="sidebar"><Brand/><div className="workspace"><span className="avatar">{user.profile.name.slice(0,1).toUpperCase()}</span><div><b>Mi espacio profesional</b><small>Cuenta personal</small></div></div><small className="nav-label">TU CARRERA</small><nav>{nav.map(([id,Icon,label])=><a key={id} href={account||admin?'/?view='+id:'#'+id} className={!account&&!admin&&active===id?'active':''} onClick={account||admin?undefined:e=>{e.preventDefault();onNav(id);}}><Icon size={19}/>{label}</a>)}</nav>{user.profile.role==='admin'&&<a className={admin?'active account-link':'account-link'} href='/admin.html'><ShieldCheck size={19}/>Administración</a>}<div className="sidebar-bottom"><div className="connection"><ShieldCheck size={19}/><div><b>Tú controlas tus datos</b><small>Portales públicos de empleo</small></div></div><a className={account?'active account-link':'account-link'} href="/account.html"><Settings2 size={19}/>Cuenta y conexiones</a><button className="logout" onClick={async()=>{await api('/auth/logout','POST');location.href='/';}}><LogOut size={17}/>Cerrar sesión</button><small className="copyright">TalentScope © 2026</small></div></aside><div className="content"><header className="topbar"><div className="crumb">Mi espacio <span>/</span> {admin?'Administración':account?'Cuenta y conexiones':nav.find(x=>x[0]===active)?.[2]}</div><a className="profile-link" href="/account.html"><span className="online"/> {user.profile.name}<span className="avatar small">{user.profile.name.slice(0,1).toUpperCase()}</span></a></header><ResumeStatus user={user}/>{children}</div></div>;}
export function Loading(){return <div className="loading"><LoaderCircle className="spin"/> Preparando tu espacio…</div>;}
export function Auth({onLogin}){const[showPassword,setShowPassword]=useState(false),[register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="auth"><div className="auth-visual"><Brand/><div><span className="eyebrow light">TU SIGUIENTE CAPÍTULO</span><h1>Las buenas decisiones<br/>empiezan con<br/><em>perspectiva.</em></h1><p>Reúne tus ofertas. Entiende sus requisitos.<br/>Encuentra dónde encaja tu talento.</p></div><small>Tu carrera merece algo más que una lista de ofertas.</small></div><main className="auth-form"><span className="eyebrow">BIENVENIDO A TALENTSCOPE</span><h2>{register?'Tu próximo paso, aquí.':'Vuelve a tu perspectiva.'}</h2><p>{register?'Crea tu cuenta. En el primer acceso deberás subir y revisar tu currículum para analizar ofertas.':'Inicia sesión para ver tus ofertas guardadas.'}</p><div className="segmented"><button className={register?'selected':''} onClick={()=>setRegister(true)}>Crear cuenta</button><button className={!register?'selected':''} onClick={()=>setRegister(false)}>Iniciar sesión</button></div><form onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{onLogin(await api('/auth/'+(register?'register':'login'),'POST',Object.fromEntries(new FormData(e.target))));}catch(x){setError(x.message);}finally{setBusy(false);}}}>{register&&<label>Tu nombre<input name="name" required placeholder="Cómo te llamas" autoComplete="name" maxLength={100}/></label>}<label>Correo electrónico<input type="email" name="email" required placeholder="tu@correo.com" autoComplete="email"/></label><label>Contraseña<input type={showPassword?"text":"password"} name="password" minLength={10} maxLength={200} required placeholder="Al menos 10 caracteres" autoComplete={register?'new-password':'current-password'}/></label><label className="check-label"><input type="checkbox" checked={showPassword} onChange={e=>setShowPassword(e.target.checked)}/>Mostrar contraseña</label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary wide">{busy?<LoaderCircle className="spin" size={18}/>:<ShieldCheck size={18}/>} {register?'Crear mi espacio':'Entrar en mi espacio'}</button></form><div className="auth-note"><ShieldCheck size={20}/><p>La conexión con LinkedIn es opcional y se realiza después. No te pediremos su contraseña.</p></div></main></div>;}
export function Score({value,size='normal'}){return <div className={'score '+size} style={{'--score':(value??0)+'%'}}><div><b>{value===null||value===undefined?'—':value+'%'}</b><small>afinidad</small></div></div>;}
export const statuses={saved:'Guardada',applied:'Solicitud enviada',interview:'Entrevista',closed:'Cerrada'};
export function Modal({title,onClose,children}){useEffect(()=>{const f=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f);},[onClose]);return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><div><span className="eyebrow">TU RADAR PROFESIONAL</span><h2>{title}</h2></div><button className="icon-button" autoFocus aria-label="Cerrar ventana" onClick={onClose}><X/></button></header>{children}</section></div>;}
