import React,{useState,useEffect,useRef} from 'react';
import {Radar,LayoutDashboard,BriefcaseBusiness,Building2,Mail,Settings2,LogOut,ArrowUpRight,ShieldCheck,LoaderCircle,Check,X,Blocks as LayersIcon} from 'lucide-react';
import './style.css';
import './remodel.css';
export async function api(path,method='GET',data){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const b=await r.json();if(!r.ok)throw Object.assign(new Error(b.error||'No se pudo completar la acción'),{status:r.status});return b;}
export function useUser(){const[user,setUser]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;async function refresh(){try{const u=await api('/auth/me');if(active)setUser(u);}catch(e){if(active&&e.status===401)setUser(null);}finally{if(active)setLoading(false);}}refresh();const timer=setInterval(refresh,30000);const focus=()=>refresh();window.addEventListener('focus',focus);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',focus);};},[]);return{user,setUser,loading};}
export function Brand(){return <a className="brand" href="/"><span className="brandmark"><Radar size={25}/></span>Junior <span>Scope</span><small>BETA</small></a>;}
export function Notice({message,onClose}){return message&&<div className="toast" role="status">{message}<button aria-label="Cerrar aviso" onClick={onClose}><X size={16}/></button></div>;}
export function Loading(){return <div className="loading"><LoaderCircle className="spin"/> Preparando tu espacio…</div>;}
let modalLocks=0,savedOverflow='';
export function Modal({title,onClose,children}){const dialog=useRef(null),close=useRef(onClose);close.current=onClose;useEffect(()=>{const previous=document.activeElement;if(modalLocks++===0){savedOverflow=document.body.style.overflow;document.body.style.overflow='hidden';}const focusables=()=>Array.from(dialog.current?.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),a[href],[tabindex="0"]')||[]);focusables()[0]?.focus();const key=e=>{if(Array.from(document.querySelectorAll('[role="dialog"]')).at(-1)!==dialog.current)return;if(e.key==='Escape'){e.preventDefault();close.current();}if(e.key==='Tab'){const nodes=focusables(),first=nodes[0],last=nodes.at(-1);if(!first)return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);if(--modalLocks===0)document.body.style.overflow=savedOverflow;previous?.focus?.();};},[]);return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={dialog} className="modal" role="dialog" aria-modal="true" aria-label={title}><header><div><span className="eyebrow">JUNIOR SCOPE</span><h2>{title}</h2></div><button className="icon-button" aria-label="Cerrar ventana" onClick={onClose}><X/></button></header>{children}</section></div>;}
